### ISSUE TITLE
OS Updates (Manual) 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1001]
Make it possible to manually start OS Updates in Stereum 

![image](https://user-images.githubusercontent.com/82385103/211322291-0f85d4a0-fad8-46ff-b77c-995f80e2ba61.png)

and change it to:

![Change it to look like this](https://user-images.githubusercontent.com/82385103/214365320-acc70a94-132a-498a-b466-6925be3d9bab.png)

The buttons will then by taken, functionality is at the time of writing not done - but will be added later.

**Comment by mabasian** [comment]
I did, it's done!

**Comment by daGscheid** [comment]
To adapt to @montajebi 's work in #1178  and finalize the modal's visuals, I propose the following changes: 

![RIGHT MENU](https://user-images.githubusercontent.com/82385103/232050833-70162bc1-02b0-416c-8f34-b72accf1d071.png)

Let me know what you think guys @montajebi & @MaxTheGeeek

**Comment by montajebi** [comment]
@daGscheid I'm up with this, Let's do this.

**Comment by daGscheid** [comment]
Closed with #1221
