### ISSUE TITLE
FR: Integrate Web3 Signer

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1002]
**Describe the solution you'd like**
A way to set up an Ethereum Node with the Web3 Signer as a validator client

Icons: (Web3 Signer has no Logo)

![Web3Signer Service](https://user-images.githubusercontent.com/82385103/211344014-31723dad-6f48-4ebc-bafd-d1fe87844114.png)
![Web3Signer - Circle](https://user-images.githubusercontent.com/82385103/211344017-60a3dcbb-65b3-491d-8428-211810dcb4de.png)

**Additional context**
- Docs can be found here: https://docs.web3signer.consensys.net/en/latest/
- Can connect to multiple Consensus Clients

**Comment by stefa2k** [comment]
doublicate? #829

**Comment by daGscheid** [comment]
Duplicate (github search you disappoint me)
