### ISSUE TITLE
BUG: Sync Status for Nethermind is Invalid 

### ISSUE THREAD

**Issue by hoduchieu01** [stereum-dev/ethereum-node#1007]
**Describe the bug**
The Sync Status of Nethermind is invalid.

**To Reproduce**

I run the node using 1-Click Installation for stake Gnosis

**Expected behavior**

The sync status of Lighthouse works normally, but the sync status of Nethermind is always 0/0. Thus, the sync status of Nethermind is invalid. I expect it shows the correct numbers.

**Screenshots**

![image](https://user-images.githubusercontent.com/23649434/211615382-6f77860c-8a9a-453b-9f4f-9e878c5c995a.png)
![image](https://user-images.githubusercontent.com/23649434/211616442-5e776926-f197-45f3-bc88-d6b3653ad7ca.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Launcher version: 2.0.0-RC.10

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Lighthouse + Nethermind

**Comment by daverolo** [comment]
Thank you @hoduchieu01 for the report. We already working on that issue in #852.
