### ISSUE TITLE
BUG: Opening client logs causes launcher to freeze

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#1107]
**Describe the bug**
when acessing logs via the launcher on an windows machine, the launcher freezes

**To Reproduce**
access logs in launcher on windows

**Expected behavior**
launcher does not freeze

**Windows Desktop:**
 - Launcher version rc13

**Comment by daverolo** [comment]
As reported in our Discord, this issue also affects Linux.
