### ISSUE TITLE
FR: Nimbus validator client

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1136]
**Is your feature request related to a problem? Please describe.**
Right now one nimbus service is configured to be the beacon client and the validator client at the same time. When updating/maintaining the beacon client it's possible that it needs some time to get to sync to function properly.

**Describe the solution you'd like**
A separate Nimbus validator client service would be also possible to configure multiple beacon clients (fallbacks) to maximise uptime.

**Comment by daverolo** [comment]
fixed with #1219 by @NeoPlays
