### ISSUE TITLE
BUG: can start update twice

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1140]
**Describe the bug**
If an update is available it's possible to click the "UPDATE ALL" button, etc. again after starting the update process already.

**To Reproduce**
1. Start update
2. Wait for it to start the tasks
3. Start update again
4. Update starts again

**Expected behavior**
Prevent user from starting updates simultaniously.

**Desktop (please complete the following information):**
 - Launcher version `1.0.0-rc.15`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Updates

**Comment by NeoPlays** [comment]
Was fixed at some point
