### ISSUE TITLE
SSV Network V3 Adaptations

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1141]
-) Make the necessary adaptation to the SSV Network Configuration to support their V3 version
 
> https://hackmd.io/@h7e5jUsiRk2Q5Bnqcrv-rg/BJOAZtokn

**Comment by JamesCarnley** [comment]
SSV Jato v3 released yesterday (https://ssv.network/jato-v3/) and operators need to migrate to the new testnet.

Will this be supported soon? Before the 2.0 full release?

**Comment by daGscheid** [comment]
> SSV Jato v3 released yesterday (https://ssv.network/jato-v3/) and operators need to migrate to the new testnet.
> Will this be supported soon? Before the 2.0 full release?

Hey James! Yeah, 100%, this high up on our priority (a little behind making sure withdrawals work). We are evaluating the necessary changes we have to make in the backend / frontend to fit the new architecture. You can expect this soon!

**Comment by daGscheid** [comment]
We walked through it. There don't seems to be any drastic Node Operator Changes - the V3 version mainly focuses on validator key distribution handling via the smart contract. @NeoPlays will test it further & then close the issue with a verdict or the necessary changes made. Can't wait for mainnet 🕺 

There are some improvements we still want to make when it comes to the SSV Network Operator Management inside of Stereum, but they are earliest tackled post 2.0.0 full release.

**Comment by daGscheid** [comment]
Api Changes required for Operator Regstration (it became annoying again). Other than that no further changes required.
