### ISSUE TITLE
BUG: Stereum Notifier blocks "Turn Node On" Command 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1147]
**Describe the bug**
With the introduction we also seem to have introduced some problems to the "Turn Node On/Off" Command. 
The Stereum Notifier seems to be effected, however takes on average longer to turn off than the others. 
The buttons activated before 

**To Reproduce**
1. Go to Node Page
2. Click "Turn Node Off" 
3. The Stereum Notifier takes forever to turn Off - blocking Turn Node On from ever showing 

**Expected behavior**
The whole Node gets turned off & I am able to turn it on again. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82385103/226582176-b6d483a8-04bf-4e97-8fd9-7b6d518fdf79.png)

**Additional context**
Seems to be a problem specific to turning off the notifier.

**Comment by NeoPlays** [comment]
The notifification service takes so long to exit, because there is no handler that listens on a `SIGTERM` signal.
Therefore the container waits 600 seconds (the configured timeout) to be timeouted and forcefully killed.
