### ISSUE TITLE
BUG: Can't update with notification service

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1163]
**Describe the bug**
Error on `update all`

```
TIME: 1680334781489819301
PLAYBOOK: /opt/stereum/ansible/controls/genericPlaybook.yaml
TASK: Get latest version for this service
ACTION: set_fact
CATEGORY: FAILED
DATA: {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'NotificationService'. 'dict object' has no attribute 'NotificationService'\n\nThe error appears to be in '/opt/stereum/ansible/controls/roles/update-services/tasks/update-service.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Get latest version for this service\n  ^ here\n", "_ansible_no_log": false}
```

**To Reproduce**
1. Setup a node with notification service
2. Update All
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/229272878-925d90f3-731b-4d3a-8c2b-dec3ce6974c0.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0.0-rc.15`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Notification service

**Comment by NeoPlays** [comment]
added it to `updates.json`
