### ISSUE TITLE
[FR]: Recommended CheckPoints for Syncing

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1177]
### Describe your idea

Additional to the current options Sync Options in the One Click Installation for Consensus Clients (Genesis & Checkpoint Sync)... 

(for reference)

![image](https://user-images.githubusercontent.com/82385103/230770543-f54cf91e-b444-4e9f-8501-4b1201a608f9.png)

...we were asked to offer an additional options, which  consists of PreConfigured checkpoints to choose between. 
I propose a dropdown menu with a selection preconfigured out of these:

Ethereum Mainnet, Goerli & Sepolia Testnet
https://eth-clients.github.io/checkpoint-sync-endpoints/

For Gnosis
https://checkpoint.gnosischain.com/

This would result in something like this:

![image](https://user-images.githubusercontent.com/82385103/230769934-1b0e8a9a-cd78-41cc-a3de-3bf7e7c5eb83.png)

IMPORTANT: This differ between networks - to offer a preselected list, it will be necessary to collect different checkpoints for

- Ethereum Mainnet
- Goerli Testnet
- Seplia Testnet
- Gnosis (

### Additional Context

This should be included in 
- [x] One Click Installation
- [x] ReSync in Node Page

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
The frontend is both visually polished and functionally stable
