### ISSUE TITLE
[FR]: Button to Export Full Logs of Service

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1209]
### Describe your idea

Some users are having troubles in the last few days and would like to show us their whole client logs. 
To do this they currently have to either make a screenshot of the logs in question or copy them by double clicking. 

To make their life easier I propose a button in the logs page, where a user could simply export & save the whole logs of a client in a text file. 

![Zeichenfläche – 4](https://user-images.githubusercontent.com/82385103/235721567-a723a8ff-f3c4-45e7-b142-35500cf3065f.png)

Button: 

![Gruppe 194](https://user-images.githubusercontent.com/82385103/235721988-11717107-3370-404a-9e5b-522c0a03b19c.png)

- [x] Discuss
- [x] Design
- [x] Build

### Considered Alternatives?

Naah, the alternative is screenshoting, which is fine but annoying. 

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
✅ Done!

**Comment by daGscheid** [comment]
Finish with #1212
