### ISSUE TITLE
[FR]: Officially Support Ubuntu 23.04

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1216]
### Describe your idea

One of our Discord User with the name QueBonic, wants us to officially support Ubuntu 23.04 "Lunar Lobster". 

https://ubuntu.com/blog/ubuntu-desktop-23-04-release-roundup

- [ ] Evaluate if any adaptions are necessary to officially support Ubuntu 23.04
- [ ] Make adaptions (if necessary)

### Considered Alternatives?

Naah, that is pretty reasonable. 

### Additional Context

https://ubuntu.com/about/release-cycle#:~:text=Releases%20of%20Ubuntu%20get%20a,every%20two%20years%20in%20April.
https://www.omgubuntu.co.uk/2023/03/ubuntu-23-04-features

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by stefa2k** [comment]
Replaced with #1591 , 23.04 is EOF next month: https://wiki.ubuntu.com/Releases
