### ISSUE TITLE
[Bug]: checkpoint sync suggestion on execution client

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1229]
### Describe the bug!

When resyncing an execution client Stereum Launcher shows checkpoint sync. There is no checkpoint sync for execution clients right now.

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/54934211/c01421a4-87eb-4965-bf9d-035ae3d343c6)

### Expected Behaviour

no checkpoint sync option

### Help us reproduce your bug!

attempt to resync an execution client

### Launcher Version

2.0.0-rc.18

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Affected Service

Execution clients

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by mabasian** [comment]
✅ it's Done!
