### ISSUE TITLE
[FR]: Integration of Reth

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1249]
### Describe your idea

Integration of [Reth](https://github.com/paradigmxyz/reth) as an execution client.

### Considered Alternatives?

-

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
Here are the logos for inside of Stereum:

![Reth - Execution Client](https://github.com/stereum-dev/ethereum-node/assets/82385103/081fdbda-db6a-4919-9e85-2fcb104c3481)
![Reth - Execution Client - Circle](https://github.com/stereum-dev/ethereum-node/assets/82385103/23d458bc-7ab5-4551-a7a0-6823e92d726b)

**Comment by stefa2k** [comment]
@daGscheid they don't look centered?
