### ISSUE TITLE
[FR]: Installation animation improvement 

### ISSUE THREAD

**Issue by PatrickRL** [stereum-dev/ethereum-node#1297]
### Describe your idea

Instead of restarting the animation from the beginning, run it backwards to create a smooth transition.

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
I think I know exactly what you want
@MaxTheGeeek is currently redoing some styles for the pne click installation, after he integrates them we can talk & fix this.
