### ISSUE TITLE
[FR]: Add machine details and a logout button to install screen

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1302]
### Describe your idea

My idea is to add two more fields **MACHINE NAME**, **IP ADDRESS** and a **LOGOUT BUTTON** to the install screen, similar to those shown on the screenshot below.

![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/d01c63e5-3493-432f-a134-33284780d31a)
### Practical reason

I have several new machines, login to one and forgot which one. Since I can't see on the install screen which one I'm on, I want to logout to start over, but that doesn't work either, so I have to close Stereum completely to start over.

With the new fields I would see where I am logged in and if it is the wrong box I could switch with the logout button.

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
Added by @erfan7r6a with #1345. Part of rc.20
