### ISSUE TITLE
[Bug]: Reboot task on node setup fails

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1303]
### Describe the bug!

Reboot task fails during node setup.

- Completely breaks the node setup
- Very likely associated to #1239

Currenlty the manual fix is:
- Close Stereum (ignore warnings if any)
- Login to the affected machine via ssh and do a manual reboot (`sudo reboot now`)
- Wait until the machine is up again
- Start Stereum and login again
- On the **Node** page click the "**TO EDIT NODE**" button
- Nuke the node and begin installation from scratch

### Attach a Screenshot!

![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/891e6123-1969-49bd-8530-0922900cf5b4)

### Expected Behaviour

System does a reboot and the node setup continues.

### Help us reproduce your bug!

Run node setup on a fresh machine that requires a restart (for example due to OS updates).

### Launcher Version

2.0.0-rc.19

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Relevant log output

```shell
TASK: trigger restart
ACTION: trigger restart
CATEGORY: OK
DATA: There is no data for these kind of tasks ¯\_(ツ)_/¯

------------------------

TASK: Could not connect 299
ACTION: Could not connect 299
CATEGORY: OK
DATA: Error: read ETIMEDOUT

299 tries left.
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
So i fixed this issue and can say that #1239 is not connected to this issue.
