### ISSUE TITLE
[FR]: Add Additional Languages

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1307]
### Describe your idea

Some of our Discord user discussed that they would like to help us expand the pool of planned supported languages of Stereum

Currently these are the following languages that we got offered:
- [x] Czech
- [x] Vietnamese

### Considered Alternatives?

No alternative - they deserve to be added as well - if we could, we would add them all. 

### Additional Context

--

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
✅
