### ISSUE TITLE
[Bug]: 2 small text errors

### ISSUE THREAD

**Issue by PatrickRL** [stereum-dev/ethereum-node#1313]
### Describe the bug!

1) Inside the Geth pruning warning window, it falsely says "notifModal.cancelText" instead of the usual "Click outside to close" 

2) When clicking on "RESYNC", it shows "OPEN LOGS" at the top instead of "RESYNC"

### Attach a Screenshot!

<img width="439" alt="Screenshot 2023-06-22 161424" src="https://github.com/stereum-dev/ethereum-node/assets/121479313/290e0c48-57e6-485c-b62f-7964032c8afb">
<img width="147" alt="Screenshot 2023-06-22 161519" src="https://github.com/stereum-dev/ethereum-node/assets/121479313/1a66249b-da5a-4133-a92d-e9de0aaa9f65">

### Expected Behaviour

1) Getting the correct close message

2) Showing the user they have selected "RESYNC"

### Help us reproduce your bug!

1) Enabling pruning on Geth to get the warning pop-up

2) Clicking on RESYNC

### Launcher Version

2.0.0-rc.19

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by mabasian** [comment]
✅
