### ISSUE TITLE
[Bug]: no v-html tag

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#1319]
### Describe the bug!

`v-html` can be a security hazard. pls look into it and maybe remove it completly or try to make it secure

### Expected Behaviour

no `v-html`

### Help us reproduce your bug!

look at `npm run lint:fix` output

### Launcher Version

latest

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by mabasian** [comment]
✅
