### ISSUE TITLE
[FR]: Status for Launcher Connection

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1321]
### Describe your idea

To show if the launcher currently has connection I would propose a status widget of the Launcher <> Server Connection, that is placed right next to the task manager in the footer. 

- [x] Online / Offline Status

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/f75c0b1a-8fc2-4e65-8b0c-ac03d529bd22)

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/cc37aa06-4fc2-4170-a841-2fac64ebac9e)

Would be nice to also show connection attempts in the footer

Nice little touch we could add if the state is offline: 

![stereum_launcher_no_connection](https://github.com/stereum-dev/ethereum-node/assets/82385103/7fa073f8-5765-4fef-925d-47e600460dc2)

![LOGO](https://github.com/stereum-dev/ethereum-node/assets/82385103/70dd993a-978a-4cea-b850-a9015ae61b41)
(top left lul)

& which brings me to another questions how should we handle going offline? 

- [ ] Is a reconnect button an option? 
Would be nice in the case of losing the connection however **considering security**, we should talk about what this would require

I would like to at least show connection reattempts if any are made

- [x] Discuss
- [x] Design 
- [x] Build

### Considered Alternatives?

Place it somewhere else. I think the users / we benefit massively from something like this. 

### Additional Context

Multiple problems with the launcher losing connection and user being irriated by pages not quite working. 

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
It's Done, but for the reconnect button I need a design to build

**Comment by daGscheid** [comment]
- [ ] Please also add a reconnecting state 
![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/d288ad55-0e93-444f-a501-d20d5e94ee24)

- [ ] Manual Reconnect Button

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/10661abc-0213-4456-be54-fa4b9f389c51)

(make it blinking, when it is available)
