### ISSUE TITLE
[FR]: Support Gnosis Withdrawals

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1322]
### Describe your idea

Gnosis Withdrawals are coming soon 🥳 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/00ea8e74-6e32-48df-af04-19525c204034)

- [ ] Make sure that Stereum supports Gnosis Withdrawals after the Shapella Upgrade has hit
- [ ] Enable withdrawals on Gnosis

### Considered Alternatives?

No alternatives

### Additional Context

--

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by NeoPlays** [comment]
I did this at some point ... should work... closing now
