### ISSUE TITLE
[FR]: three different looks for validator options

### ISSUE THREAD

**Issue by gbayasgalan** [stereum-dev/ethereum-node#1341]
### Describe your idea

would be nice to have "back" button on validator-fee-recipient, also same look
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/069d6335-f0c8-47f6-90e0-0aa521bd6fd2)
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/f1c1e0f5-a516-4de3-b7ee-b6b6db77f6eb)
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/d6986aaf-fb36-4e57-af8d-cf7991de6375)

### Considered Alternatives?

This is my idea!

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
Done!
