### ISSUE TITLE
[FR]: SSV Network - Mainnet Support

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1343]
### Describe your idea

Having gone through 4 testnet versions of SSV, we are currently getting closer & closer to a SSV Mainnet Launch.

https://ssv.network/blog/technology/mainnet-has-arrived/
The plan of the SSV Network team is to deliver the mainnet launchg in 4 stages: 

> Stage 1: Pre-Launch
> During this initial stage, the main goal is to ensure all mainnet parameters are correctly configured. The focus is on running a few permissioned validators and operators as a sanity check to ensure a smooth launch. The risk of staking ETH on the Ethereum mainnet is limited to only the core team during this phase. We want to ensure users don’t lose their ETH if something goes wrong.
> 
> Stage 2: Limited Launch
> When we are sure the network is stable for the next phase. The objective is to introduce a complete set of verified operators. Verified operators are tried and tested node runners, ensuring high performance for validators. The primary goal is to ensure the active participation of these verified operators.
> 
> Stage 3: Launch
> Here we introduce the builders utilizing ssv.network infrastructure, a.k.a Mainnet Partners! These are some of our [grant recipients](https://ssvnetwork.notion.site/e8329a6e7b3b49a8868f8776114df7bf?v=95e21089b2a94b5b9a36ac18eb22a8df) and the staking projects that have pledged to launch alongside us. Publicly staked ETH will be introduced via these partners, allowing broader participation. During the launch stage, the focus shifts to onboarding whitelisted non-verified operators, including up to 100 operators.
> 
> Stage 4: Permissionless launch
> In the true spirit of SSV, the final stage is the permissionless launch. The objective is to achieve a fully operational ssv.network launch for everyone to join. This includes the registration of permissionless operators and validators to the network. From here on, everyone can use the open protocol to build or stake. An important milestone to moving all staked ETH through DVT.

- [ ] The goal is to be ready (at latest) with the mainnet integration coming the permissionless launch. 

### Considered Alternatives?

--

### Additional Context

--

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by stefa2k** [comment]
- [ ] Adding SSV mainnet support in the OneClickInstaller
- [ ] Adding SSV service for mainnet in the custom installation

How to run on mainnet: Adding `Network: mainnet` in the ssv config should be enough.
