### ISSUE TITLE
[Bug]: Import Validator Component vanishes after playing around too much

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1349]
### Contact Details

--

### Describe the bug!

During Max and me testing, we came accross this bug. If you play around too much on the staking page the validator import vanishes

### Attach a Screenshot!

[Screen_Recording_2023-07-12_at_11-08-35 (2).webm](https://github.com/stereum-dev/ethereum-node/assets/82385103/175e1a7d-f277-478a-970b-85b535376618)

### Expected Behaviour

Don't go Validator Import :(

### Help us reproduce your bug!

-> Video

### Launcher Version

rc.19

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Affected Service

--

### Relevant log output

```shell
--
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
i fixed this with rc20 at least so far, taht when you leave the page and access it a again that the button apears again

**Comment by daGscheid** [comment]
> i fixed this with rc20 at least so far, taht when you leave the page and access it a again that the button apears again

Thanks you, awesome 🚀  I would close this then & open it again, if it should become necessary
