### ISSUE TITLE
[FR]: Add an additional button to have both "Apply" and "Apply & Restart"

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1363]
### Describe your idea

- [x] change the current button name to "Apply & Restart"
- [x] Add an additional button to the client / service settings, that can be used to run the old function of just simply applying the config, next the current implementation of "Apply & Restart" 

### Considered Alternatives?

--

### Additional Context

--

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
✅
