### ISSUE TITLE
[Bug]: Alert Box not showing all firing Grafana alerts

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1368]
### Contact Details

--

### Describe the bug!

Storage size alert is correctly showing up in Grafana, however the alert is not shown in the alert box

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/7c52ccf0-1550-44e5-8f55-7f2b1c08181f)
![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/8359f5ca-a3fd-427e-8b91-a01457623e06)

### Expected Behaviour

The alert box shows an alert for "Low Storage" whenever the storage is less than 200gb

### Help us reproduce your bug!

1. Set up Node with more than 200gb
2. Wait till the sync lets available storage shrink to < 200gb
3. Check on the Node page if the alert is shown in the alert box 
4. Go to Grafana > Alerting > Alert Rules to check if the alerts fire in Grafana

### Launcher Version

2.0.0-rc.20

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Affected Service

Lodestar <> Geth

### Relevant log output

```shell
--
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by mabasian** [comment]
that alarm still is in the firing, because of the firing alert rules. That's not a problem, just different rules

![Image](https://github.com/stereum-dev/ethereum-node/assets/54101509/cb51996e-d417-4985-a031-f4a482966b0c)
