### ISSUE TITLE
[enhancement]: improve functionality of switch button on the settings (also `default fee recipient` )

### ISSUE THREAD

**Issue by gbayasgalan** [stereum-dev/ethereum-node#1392]
### Describe the bug!

there is a switch button (toggle button) on the settings for the execution and validator clients so far. (pls see the screenshot below). 
if the user goes to the settings and change the switch button -> then `apply` also `apply & restart` buttons are activated.
 - But!!! when the user click on the switch button again (second time) then -> buttons look like still activated (to be able to click on them), although there is a nothing to change.

So the buttons should know what the current state of corresponding setting is, and react with correct state of settings, not just once when the settings page loaded.

so far it works correctly, but looks bit confused, when the user click on the switch button more than once :)

### Attach a Screenshot!

validator client: 
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/038d5637-0904-457a-9447-cb539e2c8734)
execution client: 
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/b73b58f9-fd35-4ed1-acdb-3148c69bff68)

### Expected Behaviour

1. go to the service settings (click on the `gear` icon)
2. then click on the switch button once -> then activate the `apply` and  `apply & restart` button
3. click on the switch button again (second time) -> then deactivate `apply` and `apply & restart` since there is a nothing to change (second click means it is back to the current state)

### Help us reproduce your bug!

see above! `Expected Behaviour`

### Launcher Version

2.0.0-RC.21

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Affected Service

all execution and validator services

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
#1394 broke puning.
Reopening this because #1394 is going to be reverted
