### ISSUE TITLE
[FR]: Doppelganger information before importing validator key(s)

### ISSUE THREAD

**Issue by gbayasgalan** [stereum-dev/ethereum-node#1393]
### Describe your idea

Information about `doppelganger protection` whether it is enabled or disabled -> on the popup during the `validator import` process.

I would suggest to do this on `slashing protection` popup to avoid more clicks

something like:
![Screenshot 2023-08-07 175158](https://github.com/stereum-dev/ethereum-node/assets/73820006/c9a7b888-17bf-474d-9305-6fe09ed122ee)

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
✅ Done
