### ISSUE TITLE
[FR]: Auto Detect IP of server machine in home network

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1415]
### Describe your idea

Scan for nearby local Stereum Machines installed with an offered by us ISO, using a port to make it possible to auto detect the IP in a network created with the average Standard Home Net Router

### Considered Alternatives?

----

### Additional Context

----

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
@mabasian is doing the UI to support @gbayasgalan current solution. 

To do this, lets add a button to the login form... 

![LOGIN_ENGLISH](https://github.com/stereum-dev/ethereum-node/assets/82385103/b07efd22-236f-4144-8481-95c76895fe24)

Icon
![HomeConnection_search](https://github.com/stereum-dev/ethereum-node/assets/82385103/bff61682-ccb2-4b0a-9db2-1304fe924890)


...which when pressed opens a modal, that informs about the process & where the user can manually start it. 

![LOGIN_ENGLISH – 3](https://github.com/stereum-dev/ethereum-node/assets/82385103/897c26a8-320c-4d44-bbff-2fffd25552e4)



The process will take a while...

![LOGIN_ENGLISH – 4](https://github.com/stereum-dev/ethereum-node/assets/82385103/9d6361d4-f2ed-4817-ba48-d4d08e6fe263)

...if sucessfull will yield the IP from the home network 

![LOGIN_ENGLISH – 5](https://github.com/stereum-dev/ethereum-node/assets/82385103/43829b26-716b-40ad-a794-a1f94ae85091)

**Comment by gbayasgalan** [comment]
ip scan function in backend improved. the IP address of Avado machine which connected in same device (home-router) would be found under 5 seconds.
ip range: 192.168.0.0/16
