### ISSUE TITLE
[Bug]: Task details don't refresh

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1440]
### Describe the bug!

When expanding a task to view its details the subtasks don't refresh. User needs to close the details again and open it again.

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/54934211/675f0b5b-c950-434e-a6f0-22f13ffd87f7)

### Expected Behaviour

Refreshing subtask items as the tasks do.

### Help us reproduce your bug!

Start a task, watch the subtasks.

### Launcher Version

2.0.0-rc.21

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
#1453 broke subtasks (subtask detail window automatically close)
reopening this because #1453 will be reverted
