### ISSUE TITLE
[FR]: Enhance Stereum Alerts in Alert Box

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1446]
### Describe your idea

To extend the functionality of the alert box, I propose we also make use of it for Stereum functionality

🔴 | STEREUM  | CRITICAL WARNING | Task Failed | Click to Open | <img src="https://user-images.githubusercontent.com/82385103/213940091-84b9af98-30ac-4732-af5e-f4263fc70085.png" width="50" height="50"/>  | Condition:  When Task Manager Throws an Error with a subtask | Open Subtask 
🔴 |  CLIENT / SERVICE  | CRITICAL WARNING | Synchronization Error | Click to Open | <img src="https://user-images.githubusercontent.com/82385103/202511351-db51916c-f035-4f8c-9b3a-efa7daaa7142.gif" width="50" height="50"/> | Condition: Whenever there is an error with synchronization (as specified for Synchronisation Widget) | Open Control Page

### Considered Alternatives?

--

### Additional Context

--

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by mabasian** [comment]
@daGscheid The synchronization error is indicated by a red icon, and the accompanying alert is also displayed in red. However, the red icon lacks clarity.
<img width="162" alt="Screenshot 2023-12-06 at 14 31 26" src="https://github.com/stereum-dev/ethereum-node/assets/54101509/d94a7014-2d92-48f1-a877-61cfbe7dccc5">

**Comment by mabasian** [comment]
✅
