### ISSUE TITLE
[Bug]: updating Erigon fails when updating all

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1474]
### Describe the bug!

When pressing "UPDATE ALL" and Erigon got an update as well, Erigon's pruning config get's changed always to `--prune=default` which makes it break on startup when another pruning method was configured previously.

### Expected Behaviour

Don't change pruning settings on "UPDATE ALL"

### Help us reproduce your bug!

see above

### Launcher Version

2.0.0-rc.22

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Affected Service

Erigon

### Relevant log output

```
#150: not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 --prune.r.before=11052984

#149: [EROR] [09-28|08:17:43.660] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune.h.older=90000 --prune.t.older=90000 --prune.c.older=90000 --prune.r.before=11052984"
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
"fixed" with #1479 (removed old Update Scripts)
