### ISSUE TITLE
[SSV]: Implement encrypted keys and fix small bugs

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1486]
# Summary

- [x] Implemet encrypted keys (for new setups)
- [x] Migrate raw keys to encrypted keys (for existing setups)
- [x] Equal **Expert Mode container ports** with **TcpPort and UdpPort in SSV Config file** 
- [x] Fix "**My Operator Page**" URL for specific network
- [x] Fix GUI for existing operator

# Resources:
- [SSV -> Create Configuration File](https://docs.ssv.network/operator-user-guides/operator-node/installation#create-configuration-file)
- [SSV -> Generate Operator Keys (Encrypted)](https://docs.ssv.network/operator-user-guides/operator-node/installation#generate-operator-keys-encrypted)
- [SSV -> How do I migrate raw (deprecated) Operator Keys](https://docs.ssv.network/operator-user-guides/operator-node/installation#how-do-i-migrate-raw-deprecated-operator-keys)

# Details

Below the issues listed above are described in detail.

## Implemet encrypted keys (for new setups)

New nodes should [setup SSV with encrypted keys](https://docs.ssv.network/operator-user-guides/operator-node/installation#generate-operator-keys-encrypted) by default.
Suggestion: Extend the existing GUI to do this automatically

## Migrate raw keys to encrypted keys (for existing setups)

On existing nodes [raw (deprecated) keys should be migrated to encrypted keys](https://docs.ssv.network/operator-user-guides/operator-node/installation#how-do-i-migrate-raw-deprecated-operator-keys) with a further Stereum update.
Suggestion: Provide a new or extend the existing GUI to do this automatically

## Equal Expert Mode container ports with TcpPort and UdpPort in SSV Config file

Currently the Expert Mode container ports are **12000/udp** and **13000/tcp** 
However the ports in SSV config file are **UdpPort: 12001** and **TcpPort: 13001**

**Expert Mode container ports**
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/5d375161-1d5c-42c4-b94d-b57984d59eb1)

**SSV Config file**
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/c03d2296-c08c-4579-b73f-0cbce9860089)

## Fix My Operator Page URL

A click on the "My Operator Page" button sends the user **always** to https://explorer.ssv.network/operators/ which is for Mainnet  but other networks have a different URL. For example, Goerli should be https://goerli.explorer.ssv.network/operators 

## Fix GUI for existing Operator

After registering a new Operator the GUI changes to show current Operator settings:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/dbdad99f-f240-48d8-99db-b34daa719c35)
However, after a certain time the GUI changes again as if no Operator was registered:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/e10a9a15-2e56-4074-863d-75bdf135b557)
Then you try to register your existing Operator again with the current public key:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/3d6e7853-a2b0-4e0f-b479-91b1e92a7551)
But the process goes stuck with a never ending spinner:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/ffa2f599-6614-48b1-a4ce-061236c92660)

Make sure the GUI stays with the [already installed Operator screen](https://github.com/stereum-dev/ethereum-node/assets/107847185/dbdad99f-f240-48d8-99db-b34daa719c35) if public/secret keys are added/detectd in the SSV config file.

**Comment by daGscheid** [comment]
Talked with Martin, will do some UI to choose between the legacy key fromat & the new encrypted

Legacy stays as is, with the additional option to migrate from legacy to encrypted

The encrypted option should consist of a file selector

**Comment by daGscheid** [comment]
Here are the adapted UI to address the encrypted.

First a general change to the current SSV Page when opening the modal in the header, when a registered key is already imported

![SSV - OLD – 1](https://github.com/stereum-dev/ethereum-node/assets/82385103/f8f64496-4025-45ea-b23f-4b505ce48b92)

Note: First button displays network name

<br>
<br>

## The encrypted key setup changes


The new first steps now depend on the user & what kind of key they use. If they want to continue using a raw (unencrypted) private key, they can - however joining now is the option the generate a encrypted & as well to import one

![SSV – 1](https://github.com/stereum-dev/ethereum-node/assets/82385103/226e42b8-5fda-4ee1-b3e9-446ecf1e2017)



### RAW SETUP STEPS

NOTE: Here we want to over to migrate the keys to encrypted ones

STEP | IMAGE
--- | ---
1# | ![SSV - OLD](https://github.com/stereum-dev/ethereum-node/assets/82385103/bef22888-d2ce-441e-af3f-fc0ea8c45ec6)
2# | ![SSV - OLD – 10](https://github.com/stereum-dev/ethereum-node/assets/82385103/ad0208f2-e50e-468d-ab7f-bac447e40600)

### GENERATE ENCRYPTED KEY

STEP | IMAGE
--- | ---
1# |  ![SSV - OLD – 1](https://github.com/stereum-dev/ethereum-node/assets/82385103/6b0eba54-488b-49cf-a8eb-e792f87a60eb)
2# | ![SSV - OLD – 3](https://github.com/stereum-dev/ethereum-node/assets/82385103/b301d7af-8d19-4fe0-90a9-929addc9494e)
3# | ![SSV - OLD – 4](https://github.com/stereum-dev/ethereum-node/assets/82385103/04b8b4d5-be74-4e33-9416-c41d3adf1363)
4# | ![SSV - OLD – 5](https://github.com/stereum-dev/ethereum-node/assets/82385103/7a72d154-59e1-4547-91e8-99c8bd032ea3)
5# | ![SSV - OLD – 8](https://github.com/stereum-dev/ethereum-node/assets/82385103/7ea6e04c-a144-474c-ba84-b0d376145646)
6# | ![SSV - OLD – 9](https://github.com/stereum-dev/ethereum-node/assets/82385103/cec11087-c8d0-4b67-b502-9c9c332098b2)


### IMPORT ENCRYPTED KEY

STEP | IMAGE
--- | ---
1# | ![SSV - OLD – 2](https://github.com/stereum-dev/ethereum-node/assets/82385103/4faa0a0e-0f97-4558-8a11-c0de328c2fd5)
2# | ![SSV - OLD – 6](https://github.com/stereum-dev/ethereum-node/assets/82385103/378c858f-49ac-4f6a-ad95-7e9090ea2ef7)
3# | ![SSV - OLD – 7](https://github.com/stereum-dev/ethereum-node/assets/82385103/08e04969-2a1d-4dff-bd48-68d42062cebc)
