### ISSUE TITLE
[OBOL]: Add MEV-Boost support

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#1488]
## Feature
It should be possible to configure an Obol Node to run MEV-Boost. (via Custom Installation)

## ToDo:

- [ ] Include Obol for MEV connections
- [ ] when connceting Obol to MEV include the necessary tags in the connected VC

### What happens when the user tries to connect Obol with MEV-Boost but is not connected to a (supported) VC?
t.b.a.
### Do we want to create a preset in OneClickInstallation?
t.b.a.
### we could include it in the obol dashboard (header).
t.b.a.

**Comment by daGscheid** [comment]
As the config changed of Obol this issue is no longer relevant
