### ISSUE TITLE
[FR]: Relays for Holesky

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#1490]
### Describe your idea

Add all mev boost relays for Holesky testnet.

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
There are, as far as I know, currently no available Holesky Relays. Will keep an eye on it

**Comment by NeoPlays** [comment]
https://github.com/flashbots/mev-boost/pull/585

**Comment by daGscheid** [comment]
https://boost-relay-holesky.flashbots.net/ Link

Icon is the already existing flashbots one

**Comment by mabasian** [comment]
✅ Updated

**Comment by daGscheid** [comment]
#1574
