### ISSUE TITLE
[Bug]: imported validators' number doesn't refresh after validator import/remove

### ISSUE THREAD

**Issue by gbayasgalan** [stereum-dev/ethereum-node#1533]
### Describe the bug!

imported validators' number doesn't refresh automatically after validator import/remove on the Staking page. see the screen shot

tested with lighthouse & nimbus

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/0e719363-4817-4a34-91ea-6ecba76dfdbb)

### Expected Behaviour

automatically refresh after import/remove validator(s) 

### Help us reproduce your bug!

go to staking page remove/import validator key, then look at the number of imported validators

### Launcher Version

2.0.0-rc.23

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Affected Service

lighthouse & nimbus

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by daGscheid** [comment]
Was fixed with https://github.com/stereum-dev/ethereum-node/pull/1608
