### ISSUE TITLE
[FR]: export pre-singed exit messages for heirs

### ISSUE THREAD

**Issue by karimakacem** [stereum-dev/ethereum-node#1551]
### Describe your idea

GUI fronted process to pre-sign and export voluntary exit messages that can be saved for heirs with instructions so they can easily retrieve staked eth.

similar to eth-do method, but non-cli user-friendly process

ref: https://www.reddit.com/r/ethstaker/comments/12oc85p/presign_exit_messages_for_your_heirs_with/

### Considered Alternatives?

This is my idea!

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
I think that is a cool idea! Thank you for the suggestion 🙏

**Comment by gbayasgalan** [comment]
> I think that is a cool idea! Thank you for the suggestion 🙏

Do we have some Design for UI?

**Comment by gbayasgalan** [comment]
![image](https://github.com/stereum-dev/ethereum-node/assets/73820006/ef6113fd-39a0-45e3-89a8-cbc924b7c847)
atm `export message` button added on the exit-validator (screen shot above)
