### ISSUE TITLE
[Bug]: Server Management accessible on Node Setup

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#1564]
### Describe the bug!

https://github.com/stereum-dev/ethereum-node/assets/80448387/ab5f8e80-1b64-45fb-af38-c7a123f5c536

- [X] I looked through the existing bugs of this project

**Comment by daGscheid** [comment]
This is no longer the case, thanks to the work of @mabasian & @MaxTheGeeek
