### ISSUE TITLE
[Bug]: Monitoring Options are removed with all Presets when accessing Stereum On Arm Preset first

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1566]
### Contact Details

--

### Describe the bug!

Basically whenever you access Stereum on Arm Preset in the One Click Installation, return & pick a different one - despite the Monitoring options being checked, the are removed from the other presets

### Attach a Screenshot!

https://github.com/stereum-dev/ethereum-node/assets/82385103/55acdcea-d0b1-43ef-a55d-0ad884c5112a

### Expected Behaviour

I expected it not to happen & show the monitoring options as well

### Help us reproduce your bug!

1. Go to One Click Installation, select the Stereum on ARM preset
2. Go back to the preset selection screen & pick a different preset
3. The monitoring will be gone from the "Installed Services"

### Launcher Version

2.0.2

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Affected Service

--

### Relevant log output

```shell
--
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment]
was fixed at some point ¯\_(ツ)_/¯
