### ISSUE TITLE
Fix CSS on Welcome Screen

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#157]
When building launcher the Welcome screen looks different.

How it should look:
![image](https://user-images.githubusercontent.com/54934211/162397842-851e3ba8-0d5e-48d9-8071-c162b474dfcb.png)

How it looks like:
![image](https://user-images.githubusercontent.com/54934211/162397873-014b5a64-ff11-40cb-a210-295e64cacaba.png)

**Comment by NeoPlays** [comment]
### Fixed
<img width="795" alt="grafik" src="https://user-images.githubusercontent.com/80448387/169254260-21807bba-6c3b-46a6-9273-480cf3584998.png">
