### ISSUE TITLE
[Bug]: Log Lines - Horizontal Scrollbar Too Small 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1579]
### Contact Details

--

### Describe the bug!

One of our Discord community members critiqued that the scroll bar on the logs line in the service are to small to interact with, maybe we could find an easier way to scroll this, or just make the scroll bar bigger? 

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/79b05e2a-5866-4c14-8bc3-2e8ed153fa0d)

### Expected Behaviour

I expected it to be easy to scroll

### Help us reproduce your bug!

Go to the logs, you will see in a log line that the bar is really small

### Launcher Version

2.0.1

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Affected Service

All

### Relevant log output

```shell
--
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by MaxTheGeeek** [comment]
Then we need to make the log row bigger and same for the scrollbar.

**Comment by daGscheid** [comment]
Addressed with: https://github.com/stereum-dev/ethereum-node/pull/1611 
Hopefully stays that way :)
