### ISSUE TITLE
OneClickInstallation: Default value for "Installation Path"

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#158]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/54934211/162398383-cea1580d-2cde-4e23-9504-92a73bafa5df.png">

Please use a default value like `/opt/stereum`.

**Comment by maxbehzadi82** [comment]
Is user allowed to change the default path?

**Comment by stefa2k** [comment]
> Is user allowed to change the default path?

Yes, the default should be `/opt/stereum` but users can change it to whatever they want. I'd suggest validation comes with a later release.
