### ISSUE TITLE
[Bug]: Removing and Adding Services in Custom Installation doesn't work 

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#1642]
### Describe the bug!

Add Geth, Add Lighthouse CC, connect to geth, remove CC and add it again.

Click on Confirm and it fails.

### Launcher Version

2.0.3

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Affected Service

probably all

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by daGscheid** [comment]
The confirm changes list however reacts really badly to this: 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/b3228add-5a85-488e-b61c-f8e2bfd595db)

**Comment by daGscheid** [comment]
Will close this, as this is no longer the case
