### ISSUE TITLE
[Bug]: MEV is loosing configured releays if client changes

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1720]
### Describe the bug!

At least on Holesky Network, MEV-boost config is loosing specified releays if added to a different client

### Attach a Screenshot!

MEV configured to Nimbus with a few releays specified
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/892c3894-4b4b-43ad-ab22-8a8ffe9bcf78)
Installed Lighthouse and configured MEV to Lighthouse via "Edit Node" - releays was automatically set to null
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/95b54833-e186-4596-a3b2-e16ff900376b)

### Expected Behaviour

I expected it to keep releays configured as is.

### Help us reproduce your bug!

1. Setup a node with MEV on Holesky via oneclickinstall
2. After installation open MEV config and add some releays manually
3. Go to Edit Node and install a second client, for example Lighthouse
4. Reconfigure MEV to use Lighthouse
5. Click "Confirm Changes"
6. Wait that changes are applied (see Taskmanager)
7. Go back to the default Node page
8. Open MEV settings and you will see relays as "null"

### Launcher Version

2.0.3

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Affected Service

Flashbots MEV-boost 1.7a1

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by daGscheid** [comment]
Probably addressed by: https://github.com/stereum-dev/ethereum-node/pull/1707
