### ISSUE TITLE
[FR]: Local Developer Network Setup in UI

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1729]
### Describe your idea

Give the user the possibility to set up a Local Devnet with Stereum

### Considered Alternatives?

--

### Additional Context

https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

### Acknowledgment

- [X] I looked through the feature requests/enhancements planned for this project before submitting a new idea

**Comment by daGscheid** [comment]
genesis.json for reference: 
https://github.com/OffchainLabs/eth-pos-devnet/blob/master/execution/genesis.json

**Comment by gbayasgalan** [comment]
chain IDs: https://chainlist.org/

**Comment by daGscheid** [comment]
![CONFIGURATION DISPLAY – 13](https://github.com/user-attachments/assets/d158e20b-337e-49f9-8e72-806eda199ff8)
![CONFIGURATION DISPLAY – 9](https://github.com/user-attachments/assets/1389bb9c-30c2-4dec-b5b1-dc058e8c2b32)
![CONFIGURATION DISPLAY – 10](https://github.com/user-attachments/assets/309f1e13-debf-408b-877e-34d707027c40)
![CONFIGURATION DISPLAY – 12](https://github.com/user-attachments/assets/08129482-dbbc-4824-bc95-006cb361643b)

**Comment by gbayasgalan** [comment]
1. Fix uploading genesis.json (works not properly!)
![image](https://github.com/user-attachments/assets/45d15809-5ef6-44d2-8972-dc3dc7f1751c)
2. Animating the creation and startup of services during the "devnet" setup
3. disable (filter) change network for "devnet" 
![image](https://github.com/user-attachments/assets/ea96b8e4-562c-4d2b-8b25-d029320ee5fd)
make the list empty (filter = "devnet")
![image](https://github.com/user-attachments/assets/4098f80f-d493-4f80-87d1-12b27f742b63)
