### ISSUE TITLE
[Bug]: Nimbus Consensus Client does not start after one-cllick-installation

### ISSUE THREAD

**Issue by M4r71nW** [stereum-dev/ethereum-node#1738]
### Describe the bug!

Nimbus Consensus Client does not start: 

Error response from daemon: No such container: N/A

12:21:34.871 › using playbookRunRef:  3a8903fe-5682-3822-df92-8b22e6161715
Error occurred in handler for 'manageServiceState': Error: Failed running 'starting Service': <stderr empty>
    at NodeConnection.runPlaybook (webpack://stereum-launcher/./src/backend/NodeConnection.js?:369:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack://stereum-launcher/./src/background.js?:269:10)
    at async node:electron/js2c/browser_init:2:98069

TIME: 1709551363918340683
PLAYBOOK: /opt/stereum/ansible/controls/genericPlaybook.yaml
TASK: log checkpoint sync result
ACTION: debug
CATEGORY: FAILED
DATA: {"msg": {"changed": false, "stdout": "NTC 2024-03-04 11:10:31.685+00:00 Starting trusted node sync                 databaseDir=/opt/app/beacon/db backfill=true reindex=false syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/\nNTC 2024-03-04 11:10:31.715+00:00 Downloading checkpoint state               syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized\nERR 2024-03-04 11:11:31.716+00:00 Attempt to download checkpoint state timed out syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized\nNTC 2024-03-04 11:21:42.263+00:00 Starting trusted node sync                 databaseDir=/opt/app/beacon/db backfill=true reindex=false syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/\nNTC 2024-03-04 11:21:42.326+00:00 Downloading checkpoint state               syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized\nERR 2024-03-04 11:22:42.329+00:00 Attempt to download checkpoint state timed out syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized", "stderr": "", "rc": 0, "cmd": ["docker", "logs", "nimbus-checkpointsync"], "start": "2024-03-04 11:22:43.846577", "end": "2024-03-04 11:22:43.863135", "delta": "0:00:00.016558", "msg": "", "stdout_lines": ["NTC 2024-03-04 11:10:31.685+00:00 Starting trusted node sync                 databaseDir=/opt/app/beacon/db backfill=true reindex=false syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/", "NTC 2024-03-04 11:10:31.715+00:00 Downloading checkpoint state               syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized", "ERR 2024-03-04 11:11:31.716+00:00 Attempt to download checkpoint state timed out syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized", "NTC 2024-03-04 11:21:42.263+00:00 Starting trusted node sync                 databaseDir=/opt/app/beacon/db backfill=true reindex=false syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/", "NTC 2024-03-04 11:21:42.326+00:00 Downloading checkpoint state               syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized", "ERR 2024-03-04 11:22:42.329+00:00 Attempt to download checkpoint state timed out syncTarget=finalized restUrl=https://beaconstate.ethstaker.cc/ stateId=finalized"], "stderr_lines": [], "failed": false}, "_ansible_verbose_always": true, "_ansible_no_log": false, "changed": false, "failed_when_result": true}

### Expected Behaviour

I expected it to

### Help us reproduce your bug!

Here is how to reproduce it!

### Launcher Version

latest main branch

### Desktop OS

Linux

### Node Server OS

Ubuntu 22.04

### Affected Service

Nimbus

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by daverolo** [comment]
@M4r71nW 
- how long did you wait for the client to start?
- did the client restart?
- did the client stop completely?

for me the log looks like checkpoint sync failed. this can happen from time to time and the client usually stops and restarts several times.
