### ISSUE TITLE
[Improvement]: Change Language Navigation to Language Page in Settings

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1749]
### Describe what you do not like or what problem you ran into

The language page before the welcome is not used a lot and sadly only seen when the user first opens Stereum. I would like to change this by using it as a selector in the settings page. 

### Attach a Screenshot!

![language pagges](https://github.com/stereum-dev/ethereum-node/assets/82385103/a02be6f3-7751-4541-a8e8-d0ef5f6a1b0a)

### Suggestion Box for Improvement

After @ithilion2007 has handed us the necessary adapted animation for the language page (as the animation end entering the page), I would like to change it so the user has the chance to see the language page again accessing it through the settings. 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/68bf5969-c09f-4d66-ae37-ac56d44e33ed)

### Launcher Version

2.0.3

### Desktop OS

Windows

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing issues of this project

**Comment by mabasian** [comment]
Fixed with the PR #1812
