### ISSUE TITLE
[Bug]: Feedback, Testing & Suggestions in Credit Tab doesn't load

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1765]
### Contact Details

--

### Describe the bug!

The Feedback, Testing & Suggestions that is working with the stereum.net api, is not loading in the builded application despite working in the dev version  

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/8c1b6b2d-7ce5-4ed3-b4f8-8a15823d6d74)

### Expected Behaviour

I expected it to load the list correctly

### Help us reproduce your bug!

1) Open Stereum
2) Visit Stereum Settings
3) Enter "Feedback, Testing & Suggestions in Credit Tab doesn't load"

### Launcher Version

2.1.0

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Affected Service

--

### Relevant log output

```shell
--
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by mabasian** [comment]
Fixed with the PR #1792
