### ISSUE TITLE
Take out deprecating Goerli Testnet from Network Config

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1777]
Goerli is nearing the end of its lifetime. While there is still attestations going on, a lot of services have started to wind down. 

This issue is to track this process, of removing Goerli from the config and network selection in Stereum.

RIP Goerli Prater

**Comment by daGscheid** [comment]
Replaced for test in:
https://github.com/stereum-dev/ethereum-node/pull/1854

Taken out of Updates.json

Disabled for now with:
https://github.com/stereum-dev/ethereum-node/pull/1869

@mabasian is going to gracefully remove it from the application 😄

**Comment by mabasian** [comment]
✅ Done!
