### ISSUE TITLE
[Improvement]: Estimated Time to Activation for Pending Keys

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1801]
### Contact Details

--

### Describe what you do not like or what problem you ran into

After having deposited for the validator key and before it has gone through activiation queue, the valiator shows now NaaN for "online since"

### Attach a Screenshot!

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/6ee8ffb4-ac20-41ba-ba97-2d3a8f0dae21)

### Suggestion Box for Improvement

One of our Discord community members, t-spark, suggested, that we use this space to instead show an estimation to the activation of the pending key.

### Launcher Version

2.1.1

### Desktop OS

All

### Node Server OS

Ubuntu 22.04

### Acknowledgment

- [X] I looked through the existing issues of this project

**Comment by Nirgello** [comment]
Of course it would be nice to see the calculated waiting-since-active time or waiting-since-exit time.

**Comment by daGscheid** [comment]
We will handle with this issue: 
- Deposited since
- Withdrawal Since
- Exit Since
