### ISSUE TITLE
[Bug]: SSV Network Modal - Wrong Network Displayed

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1825]
### Environment

Release

### Bug Description

The network icon in the SSV Modal shows the wrong network when hovered

F.e.: here I am on Mainnet
![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/20fb9281-f2ea-4970-bbc7-644481995f9e)

### Launcher Version

2.1.2

### Operating System

Windows

### Affected Service (if applicable)

--

### Logs (if applicable)

```shell
--
```

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by mabasian** [comment]
Fixed with the PR #1835
