### ISSUE TITLE
[Enhancement]: Allow import and export of saved server list

### ISSUE THREAD

**Issue by domioiRL** [stereum-dev/ethereum-node#1858]
### Describe the enhancement

It would be a nice QoL change to allow users to import and export the saved servers (config.json) so it can be used on another device.

### Acknowledgment

- [X] I have reviewed the existing enhancements and confirm that this suggestion is unique.

**Comment by daGscheid** [comment]
![image](https://github.com/user-attachments/assets/8b0e1492-ae50-475c-8917-5cfc3038cd00)
Should follow Max StereumPlus PR, adding two more buttons@mabasian
