### ISSUE TITLE
[Bug]: Node Setup Workflow UI issue

### ISSUE THREAD

**Issue by Vithya-RS** [stereum-dev/ethereum-node#1859]
### Environment

Production

### Bug Description

In the node setup flow, navigate to set blockchain sync (Set how the Node clients where synchronize their blockchain data from)  
Under Consensus (Lighthouse), Click on source dropdown (Checkpoint Sync) and click on the “>" button to move to custom source option/ syncs from genesis, the dropdown option is still open, and selecting any option at this point will not work

Expected Behaviour: Either close the dropdown list once moved to next option or disable the “>" button when dropdown is open.
<img width="969" alt="Screenshot 2024-04-26 at 4 05 41 PM" src="https://github.com/stereum-dev/ethereum-node/assets/156310483/b3bcd26c-701a-4689-bd04-05ed4cf6462e">

### Launcher Version

2.1.3

### Operating System

Mac

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by daGscheid** [comment]
Fixed with: https://github.com/stereum-dev/ethereum-node/pull/1928
