### ISSUE TITLE
[Bug]: Wrong peers count for Lighthouse in P2P widget

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1862]
### Environment

production

### Bug Description

Lighthouse shows max 88 peers while in the logs i can see 110 peers:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/752f2d6a-e5d3-4ad8-ae2a-90a8c81b5870)
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/a644037c-8b4f-4c01-bd84-0cd061ebf6ff)

It seems that Lighthouse has changed `--target-peers` default value from `80` to `100`.
In the docs i can still read 80 + 10% but on my node i usually have `110` peers without changing `--target-peers` value.

### Solution
Change Lighthouse `--target-peers` default value (`defval`) in [Monitoring.js](https://github.com/stereum-dev/ethereum-node/blob/f35009a9277f54d2e0a1c6a7563b567a188a263b/launcher/src/backend/Monitoring.js#L1460) to `100`

### Launcher Version

2.1.3

### Operating System

Mac

### Affected Service (if applicable)

Lighthouse >= 5.0.0

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by NeoPlays** [comment]
this is fixed
