### ISSUE TITLE
[Enhancement]: Implement connection check

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1863]
### Describe the enhancement

Implement a check that shows a popup message and allows a re-login on button click if the connection to the node is _bad_.

### Reason
We got several reports of users that just see freezing cards at some point, usually due to a bad internet connection:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/4e949281-7c39-463a-a421-2999b1d615d9)

### Additional Context

@MaxTheGeeek and @NeoPlays mentioned some events of [Electron](https://www.electronjs.org/docs/latest) that can be used to monitor the connection and the current state of the application window.
If the connection reaches a certain point that is defined as "bad" a trigger should be executed to pass this information to the UI.

### Acknowledgment

- [X] I have reviewed the existing enhancements and confirm that this suggestion is unique.

**Comment by daGscheid** [comment]
We have more room with the upcoming changes for #1638 

![change](https://github.com/stereum-dev/ethereum-node/assets/82385103/3f1a389e-5534-4635-aa9f-a80da8a0a21b)
(early version)

And we will use this to fullfill this task.

**Comment by daGscheid** [comment]
Completed with: https://github.com/stereum-dev/ethereum-node/pull/1809
