### ISSUE TITLE
[Bug]: Error when exiting individual keys with Nimbus VC

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1913]
### Environment

Release

### Bug Description

When attempting to exit an individual TESTNET key on the staking page, one of our Discord community members ran into this problem: 

![Exit_Fehlermeldung](https://github.com/stereum-dev/ethereum-node/assets/82385103/19c3c0b7-e96f-4198-bdaa-7694dc39bfcb)
![Leeres_Exit_Fenster](https://github.com/stereum-dev/ethereum-node/assets/82385103/9b029af8-33b0-45bf-8afb-3ee29cb1d13c)

### Launcher Version

2.1.5

### Operating System

Windows

### Affected Service (if applicable)

Nimbus VC

### Logs (if applicable)

```shell
--
```

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by gbayasgalan** [comment]
Slight UI issue: After a validator successfully exits, the UI does not display the 'Successfully exited' message. Instead, it shows nothing in the pop-up, while the Task Manager correctly indicates that the validator account has exited.
