### ISSUE TITLE
[COLLECTION]: Multi Config Integration - Troubleshooting Collection

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1918]
This issue is to collect problems with the merged Multi Config feature with #1809 

- [x] Beaconcha.in Notification Service Improvements @mabasian

- [x] Edit Node Page - Service Selection Filter doesn't apply for multi config @MaxTheGeeek 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/3cd6c5c4-f074-4705-ac6b-d1cb800d9d10)

- [x] Alert Box in Front of Modals on Node Page @mabasian 

- [x] Staking Page - Filter Validator Clients based on Service ID Filter when importing @MaxTheGeeek 

- [x] Staking Page - Filter Validator Clients based on Selected Setup @MaxTheGeeek 

- [x] Staking Error - StakingScreen Line 183 @MaxTheGeeek 

- [x] Filter out Server Setup when there is no Validator Client from Staking Page Dropdown @MaxTheGeeek 

- [x] Adding new carroussel for Checkpoint Sync @MaxTheGeeek (also fixes: https://github.com/stereum-dev/ethereum-node/issues/1859)

- [x] Change Chain Docs Wording & Link to lead instead to https://stereum-dev.github.io/ethereum-node-web-docs/ @mabasian 
![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/5526a743-ab5e-441c-8ad8-a2b3d64d6b01)

![help-modal-doc-stereum docs](https://github.com/stereum-dev/ethereum-node/assets/82385103/c50004b0-1d20-423d-b0b3-7d9a81e849f2)

- [x] #1923

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/bab4d8db-d12d-4876-9217-3e1e6763a614)

- [x] Filter on Control Page doesn't work correctly @mabasian 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/3fc5f29d-ec6e-45a1-a968-e13e20587468)

- [x] There should be no server view selectable on Control Page (for now) & default should be the first setup @mabasian 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/fa03a8e5-0d93-4d39-8722-ee72dac45df2)

- [x] Add coloring for validator keys based on setup 

![image](https://github.com/stereum-dev/ethereum-node/assets/82385103/85fb4f14-e5f1-417d-878e-9058aafb6f18)

- [x] If there is only 1 Setup present on the machine, make it the default selection.

**Comment by mabasian** [comment]
<img width="1029" alt="Screenshot 2024-07-02 at 13 31 55" src="https://github.com/stereum-dev/ethereum-node/assets/54101509/5ad5621a-297b-4923-99bc-d8e16e228ad7">
user cannot select an option to resync in one click installation

**Comment by daverolo** [comment]
suggestion to change icon behaviour from `onmouseover` to `onclick`, like we have it on all other services in edit node. currently this is toggle in/out constantly without moving the mouse (see video) and i tend to instantly click on the label and hit the delete button by accident. if i don't look closely right top and just continue with the service editing, it will delete my whole node setup by accident:
https://github.com/user-attachments/assets/7406ffc3-e9fa-4e03-956f-926b53640cd9

or maybe we should consider this as a bug in general? see second video below. this would delete the whole node setup/services but i acted like a user that would have probably just want to edit/remove one service -> ssv in my example.
what i mean is: if the user moves forward (clicks the `Config Page` button) to edit the services, the previous setup changes should be removed from the confirmation queue. or am i wrong with that?
https://github.com/user-attachments/assets/4e6f7e74-e052-45b8-93c1-a8059dabe6a9

**Comment by daGscheid** [comment]
Last Task finished with: https://github.com/stereum-dev/ethereum-node/pull/1945
