### ISSUE TITLE
[Bug]:  --disable-enr-auto-update flag for LighthouseBeaconService should not have value

### ISSUE THREAD

**Issue by scripnichenko** [stereum-dev/ethereum-node#1926]
### Environment

production

### Bug Description

Based on [documentation](https://lighthouse-book.sigmaprime.io/help_bn.html?highlight=--disable-enr-auto-update#beacon-node) the `--disable-enr-auto-update` is a flag not a map.

>       --disable-enr-auto-update
>           Discovery automatically updates the nodes local ENR with an external
>           IP address and port as seen by other peers on the network. This
>           disables this feature, fixing the ENR's IP/PORT to those specified on
>           boot.

ℹ️ `controls/roles/update-changes/molecule/215/prepare.yml` should be updated. 

💁  Currently LighthouseBeaconService service is erroring and not able to start

------

<img width="1043" alt="image" src="https://github.com/stereum-dev/ethereum-node/assets/4344096/6be9ecfa-7481-43fc-93a6-b28ee77e8a36">

### Launcher Version

2.1.5

### Operating System

Mac

### Logs (if applicable)

```shell
Usage: lighthouse beacon_node --debug-level <LEVEL> --network <network> --execution-endpoint <EXECUTION-ENDPOINT> --execution-jwt <EXECUTION-JWT> --eth1-blocks-per-log-query <BLOCKS> --datadir <DIR> --http-address <ADDRESS> --metrics --metrics-address <ADDRESS> --disable-upnp --validator-monitor-auto --slasher --slasher-dir <PATH> --port <PORT> --enr-tcp-port <PORT> --enr-udp-port <PORT> --disable-enr-auto-update <--http|--gui|--staking>

error: unexpected value 'false' for '--disable-enr-auto-update' found; no more were expected
```

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by daverolo** [comment]
Thank you for the report. The bug is already fixed by @NeoPlays with #1912 
You can just update your node to get the Lighthouse hotfix:
![grafik](https://github.com/stereum-dev/ethereum-node/assets/107847185/71fc9a13-312c-4856-be8f-0082440dce4f)
