### ISSUE TITLE
[Bug]: Checkpoint sync for EC selectable in resync dialog

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#1998]
### Environment

production

### Bug Description

Besu as a EC cannot checkpoint sync but it can be selected in the dialog:
![grafik](https://github.com/user-attachments/assets/110e3978-cbb5-4064-a42d-a5f4eeb35a9a)

### Launcher Version

2.2.1

### Operating System

Mac

### Affected Service (if applicable)

All

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by mabasian** [comment]
This issue has been resolved in my PR #1996. Please fetch the latest updates.
