### ISSUE TITLE
[Bug]: OS Updates list does not refresh

### ISSUE THREAD

**Issue by daverolo** [stereum-dev/ethereum-node#2034]
### Environment

Development

### Bug Description

1. Executed OS updates
![image](https://github.com/user-attachments/assets/a5f057dc-1564-4edf-a405-5dfa25ca1ce2)
2. After the update was done the machine rebooted and Stereum automatically re-connected to the node.
However, the update count and the update list was still the same as before the update/reboot.
![image](https://github.com/user-attachments/assets/ad1ccea5-5d25-4794-930e-4b2a4319c80d)
![image](https://github.com/user-attachments/assets/eec31127-b90b-434e-98a3-73e55d65b7ca)
3. Logged out manually
![image](https://github.com/user-attachments/assets/fd506c7f-f6e3-4cc1-b99a-edce886f26a9)
4. On next login the update list was as expected
![image](https://github.com/user-attachments/assets/34294345-2635-4704-878b-36258c2fed11)
![image](https://github.com/user-attachments/assets/f3aa203f-12cc-4a4c-af64-f1721b81fd53)

### Launcher Version

main:39b902327ce03a2ccb90fb604279240c842a5e5f

### Operating System

Mac

### Affected Service (if applicable)

OS updates (panels)

### Acknowledgment

- [X] I have checked the existing bugs and confirmed this issue is not already reported.

**Comment by NeoPlays** [comment]
#2019
