### ISSUE TITLE
[Enhancement]: Client Option to easily add / delete the Slasher for Lighthouse

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#2073]
### Describe the enhancement

Add an option to the client settings of Lighthouse to easily add / delete the Slasher Lighthouse installs. 

### Dependencies

--

### Additional Context

--

### Acknowledgment

- [X] I have reviewed the existing enhancements and confirm that this suggestion is unique.

**Comment by NeoPlays** [comment]
To remove the slasher from Lighthouse CC you need to do the following:
- remove slasher tags from config (`--slasher` and `--slasher-dir`)
- remove slasher volume `working-dir + /slasher:/opt/app/slasher`
- remove left files in slasher directory (working-dir + /slasher)
