### ISSUE TITLE
[Enhancement]: One-Click Server Configuration Import from StereumPlus.com

### ISSUE THREAD

**Issue by MaxTheGeeek** [stereum-dev/ethereum-node#2131]
## Purpose
Add an integration feature between stereumplus.com and the Stereum Launcher that allows users to directly import the purchsed server configurations with a single click

## Requirements

- [ ] Implementing a custom URL mechanism to transfer server configuration data
- [ ] Enabling automatic configuration import and Stereum Launcher app launch

### Acknowledgment

- [X] I have reviewed the existing enhancements and confirm that this suggestion is unique.

**Comment by daGscheid** [comment]
Added with: https://github.com/stereum-dev/ethereum-node/pull/2136
