### ISSUE TITLE
OneClickInstaller: Setup Blox SSV operator node

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#227]
A user should be able to select the "Blox SSV" in One Click Installer and setup an operator node with it.

Services needed:
- geth
- one of the consensus client (lighthouse, nimbus, prysm, teku)
- blox ssv service https://hub.docker.com/r/bloxstaking/ssv-node

The setup should automatically generate the ssv keys with ansible role `ssv-key-generator` (see #223 for details).

**Comment by NeoPlays** [comment]
When should the ssv keys be written into `/data/config.yaml`? on setup or on registration together with the `RegistryContractAddr` (Ethereum Address? #228) ?

**Comment by stefa2k** [comment]
On setup, the setup can already generate the key pair (public key & secret key).

Doesn't matter much, even if the user later replaces it there's no harm done and the user has a running service when completing the setup.
