### ISSUE TITLE
Show keys of Blox SSV operator node service

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#228]
@daGscheid please define in this issue how to show the secret & public key of the operator node. Also define how to link to the node operator page of https://app.prater.ssv.network/

**Comment by daGscheid** [comment]
I thought I would write down all my thoughts about the frontend registration process here. 
The flow of registration after having installed the SSV Network Component should look in my mind something like this: 

![SSV FLOW](https://user-images.githubusercontent.com/82385103/167294609-52098387-ad9d-429d-8c0d-f122295fb4dd.png)

After having installed the SSV component on the top bar the SSV symbol appears.  This is how you would generally interact with the SSV service. 
_(Important to consider: What if the users doesn't have all the necessary components running to run a SSV operator node? - prompt listing missing components?)_

Pressing the button they are **2 cases** we have to differ:
1) first time registering users
2) a migrating operator seeding their public operator key with their private/secret key
While not to consider for the testing versions, I would like to have some idea how we handle the 2nd case in the backend to know where to put it best in the frontend @stefa2k. Currently I am thinking about either during the setup process as installation option so you could seed the public operator key or simply via a selection before going to the registration page. 

Considering future services both cases will most likely be present in some form, and a uniformed probably not out of reach. 
Should come back to that thought when we tackle the second integration.  

![SSV FLOW – 3](https://user-images.githubusercontent.com/82385103/167294695-d292e97c-1ba4-499d-88b1-bf6f7bbc7219.png)

Considering purely the 1st case, the button leads the user to the SSV Operator Registration Page. There is an interesting questions in how to abstract the registration process. Given that it prompts a transactions. For testing a link to opening up ssv's operator page in the standard browser might be enough. I wouldn't recommend this as a lasting solution for usability reasons however. 
Here would be a suggestion for what this could like inside of Stereum:

![SSV FLOW – Unchecked](https://user-images.githubusercontent.com/82385103/167296858-c3da35be-89a9-4a00-a9d9-e0630a7c5921.png)

On the Operator Page you are asked to pick a Operator Name & put in your Ethereum Address. 
A small warning with a checkbox orders you to copy your operator private key. Pressing the copy button next to the operator private key, checks the checkbox and allows the user to proceed.  

![SSV FLOW - Checked](https://user-images.githubusercontent.com/82385103/167297111-5cd0f362-b64f-41f2-a966-a8518c6760ea.png)

Pressing "Register "prompts a transactions, writing the information into a smart contract. This will probably change over time, we will see what their V2 will look like.  

After registration you will land here: 
![SSV FLOW – 1](https://user-images.githubusercontent.com/82385103/167295018-eefbbc18-6f91-402d-82e0-d82bf0eabdf1.png)

Pressing the SSV Button will open the same page. 

The outlined commands by order are:
Copy Operator Key - Copies Public Operator Key
Operator Page - Opens your SSV Operator Page in the standard browser. The SSV Explorer Oage follows a logic that either takes the Ethereum address or the public operator key (no exact insight) to generate a weblink. 
Grafana Dashboard - SSV features their own Grafana Dashboard which you are able to navigate to here directly


The validator keys themselves will be displayed in Stereum, but this should be discussed in other issue.

**Comment by stefa2k** [comment]
Thanks @daGscheid for the explanation, for this issue it's only relevant how to show the keys (as you lined out in your UI drafts) and where the registration button goes. Let's finish this first with this issue and think later about how to solve the registration through Stereum UI.
