### ISSUE TITLE
Stable branch needs an update

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#257]
stable branch is missing new roles like `validator-import-api`
this will cause the integration test from #256 not to work.

**Comment by stefa2k** [comment]
done

**Comment by stefa2k** [comment]
on second thought, integration tests should not fail because of an unmerged stable branch. Is there a way we can dynamically switch this to a branch of choice, e. g. for integration tests picking up `main`?

**Comment by NeoPlays** [comment]
> on second thought, integration tests should not fail because of an unmerged stable branch. Is there a way we can dynamically switch this to a branch of choice, e. g. for integration tests picking up `main`?

Sure, first idea that comes to my mind would be an env var
