### ISSUE TITLE
Connect to multiple instances with Stereum Launcher

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#268]
User should be able to manage multiple Stereum nodes at the same time. @daGscheid please evaluate best solutions. To my mind comes:
- Running multiple instances of Stereum Launcher
- Tab support in the Stereum Launcher app.

**Comment by daGscheid** [comment]
Here is my current idea based on your guys feedback. A tab that can be opened by clicking the Logo in the top left. 

![EN - NODE TAB - HOME - ACTIVE – 1fff](https://user-images.githubusercontent.com/82385103/170371679-77a51621-e44a-473e-98c5-5d6c77c1940b.png)

![EN - NODE TAB - HOME –  INSTALLED – 1](https://user-images.githubusercontent.com/82385103/170371212-4f57af83-ced9-40b4-9697-f6a1e8582bfd.png)
 
 Logging into the connection revealing more details about their state. 

We talked about it last Monday, thinking about it more, how you do you see keeping the connection open ones the password is entered and until the instance of the launcher is terminated? So you can log into them one by one, and enable switching between them. Still a challenge but less of a headache for a first approach solution?

**Comment by daGscheid** [comment]
It is still on the radar, just not a foremost priority.
Plan is still to access it by clicking the Stereum Logo Left Top! 
But I would like to show the updated design for this, though it is still subject to change :D 

![ONE CLICK INSTALLATION – 15](https://user-images.githubusercontent.com/82385103/213529869-b73956bc-2d90-467b-8d47-c8ebc2c4b5f7.png)

**Comment by daGscheid** [comment]
- [ ] Include Button for FULL LOG overview in combination with #831 & eventually adapt work for #1042 to changes

**Comment by daGscheid** [comment]
Closing this - I think we found a great solution #1467 . Moved Tab Key support in here: https://github.com/stereum-dev/ethereum-node/issues/1768
