### ISSUE TITLE
Update notifier Stereum Launcher

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#269]
Stereum launcher should check available updates of the app on startup or regularly and notify the user when updates are available to download.

@daGscheid please design how this should look like.

**Comment by daGscheid** [comment]
There are two different cases of updates we have to handle:

1) Stereum Updates 
2) Plugin Updates 

To outline my thinking: For clarity there should be a space that features both to conveniently access. 
As of the topic of the issue this explanation is concentrating on the first category, updates of Stereum itself. 
The elements inside this category can than be further classified.

BEFORE LOGIN
AFTER LOGIN

In this 1# response I would like to concentrate on the update process AFTER LOGIN - given that decision made in #268 will highly influence decision made on this issue. I will summarize them again later with less blablabla in a later comment.

<br>
<br>
<br>

###BEFORE LOGIN
### NOTIFICIATION
---

Currently these are all planned spaces **`to notify`** the user of Stereum updates: 

ON ALL PAGES
--- 
![Update available Launcher](https://user-images.githubusercontent.com/82385103/169283209-ec20fd6e-b124-4011-9a42-0f9cea808571.png)

Replace left top icon with update notification. 

<br>
<br>
<br>

### INITIATION
---

Pressing the download buttons generally leads to a confirmation dialog where the version to which Stereum is updated to is presented to the user. Clicking accept makes a simple download progress bar / circle / numerals pop up. After this the Stereum would probably require a restart (@stefa2k)?
Currently these are all planned spaces where the user is able `to initiate ` the `update process of Stereum`:  


PRESSING THE LOGO NOTIFICATIONs
--- 

Pressing the notification on the logo in the top left, that is used to notify you, leads to a page with this element
![TAB MENU](https://user-images.githubusercontent.com/82385103/169286424-5cb160c6-4a8d-4342-ad23-b61d5da51b72.png)

Currently figuring out could use this page further in relation to #268 

SETTINGS
--
The Settings page is in an early design phase and should feature a block where the updates can be accessed: 

![Stereum Update](https://user-images.githubusercontent.com/82385103/169274354-1320d9c3-2ced-4ddd-930e-1807e58d3ba8.png)


> Short Explanation

LEFT TOP BUTTON ->  Opens CONFIRMATION dialog box (asked to choose version (?)) -> Initiates Download 
LEFT BOTTOM BUTTON -> Initiate Search for Updates Now. 
Installed Stereum Version -> shows current version
Latest Available Stereum Version -> most recent stable Stereum version available for download
Stereum Update Configuration -> how to handle Stereum updates - choice: auto / manual (attended / unattended)
Plug-In Update Configuration -> how to handle the updates of clients & services - choice auto / manual (attended / unattended)

Additionally a button will join this box, if we decide to activate the Stereum Testing Version that way. 


<br>
<br>
<br>

---------

Question that pop up in my mind while writing this and we / I have to consider 

- how would the user choose download the testing version for future releases? (@stefa2k) how would you like to handle this? 

In my mind we could think about: 
a) making it a One Click Installer Option - when first setting up a node - with you guys being able to define what this option looks like in every version 
b) selection - before setup of node by providing two different download packages on the website
c) selection - after setup of node - being able to choose to set Stereum into the testing mode in the settings and with this selection setting the launcher to receive updates of the public testing lane? 

Extra Note: Potential Hard Coded Testnet Restriction in place for public testing version of Stereum?

**Comment by stefa2k** [comment]
Please review if this usable with the solution in #367

**Comment by daGscheid** [comment]
Updated - reduced complexity for #561 

Pressing the Update Button on the top.... 
> FOR REFERENCE
![FLOW - VALIDATOR IMPORT – 13](https://user-images.githubusercontent.com/82385103/180093742-f06aac5d-130d-4dae-bd72-bd6cde3510f8.png)
 
....opens up the Update Module
![TAB MENU](https://user-images.githubusercontent.com/82385103/180094018-5850ae52-deca-4c72-a0e4-f6b64336fbed.png)

As you can see Stereum Application Updates, as well as client & service updates are handled. 
Pressing the button initiates the task.
