### ISSUE TITLE
Login: no response when connection is not possible to server

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#294]
When entering IP, user, etc. and clicking on "Login" the app doesn't respond. @daGscheid please find a solution to let the user know connecting is in progress. Diabling the button or something.

Also the user shouldn't be able to select what to do if connection is not possible.

**Comment by daGscheid** [comment]
Talked with @maxbehzadi82. Will use a floating loading overlay during the connection process.
