### ISSUE TITLE
Set graffiti for all validators

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#317]
Set a graffiti text for all validators. This needs to be set on all validator services running.

**Comment by daGscheid** [comment]
![GRAFFITI_ICON](https://user-images.githubusercontent.com/82385103/180083418-541e6db3-3f8d-4c57-9c24-f21d7dbb005c.png)

Here is the icon. 
As you can see in the Staking Tab - there are two buttons. One on the key itself to change the graffiti the one key...


![CHANGE GRAFFITI](https://user-images.githubusercontent.com/82385103/180084826-ece66b31-83e3-46d8-a6d1-d6794c919fdb.png)



....and of the button one on the right to change the graffiti of all validator keys (overwrites single) 

![FLOW - VALIDATOR IMPORT – 13](https://user-images.githubusercontent.com/82385103/180084832-b567d2a7-83f4-4089-bd1d-7f28544a6b1c.png)


Both buttons, when confirmed initiating a tasks in the task manager (CHANGE ALL VALIDATOR GRAFFITIS or CHANGE VALIDAOR GRAFFITI - or whatever pair).

**Comment by NeoPlays** [comment]
Per Key Graffitis is very painful to implement. Not only doesn't Nimbus and Teku support it but prysms implementation relies on knowing the validator id instead of the validating pub key like with Lighthouse.

**Comment by stefa2k** [comment]
Move this back until it's a common API.
