### ISSUE TITLE
Make memory usage of Teku service configurable

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#348]
Right now Teku's memory usage is limited to 4gb, this should be configurable via the service configuration in the UI. @daGscheid please specify how this could look like.

https://github.com/stereum-dev/ethereum-node/blob/3ed2ada0ef9cea910ee403b484b8c90dc9e76515/launcher/src/backend/ethereum-services/TekuBeaconService.js#L54

**Comment by stefa2k** [comment]
Thanks, it's not possible to specify "none", user needs to enter a valid number.

**Comment by NeoPlays** [comment]
not functional
