### ISSUE TITLE
Start & stop service via UI

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#354]
Right now it's not possible to start or to stop a service. @daGscheid please figure out how this could work on the UI.

**Comment by daGscheid** [comment]
There are two ways planned to start and stop a service in the UI:

1# NODE TAB > EDIT NODE PAGE
![StartAndStop](https://user-images.githubusercontent.com/82385103/172052434-cdedf028-7fd9-41b6-a2a9-50448e7ed974.png)

2# CONTROL TAB - LEFT MENU  
> this is a adaption to the left bars structure @maxbehzadi82 
![StartAndStop](https://user-images.githubusercontent.com/82385103/172052387-e0249e72-62db-4510-9613-7cd0fd19bc93.png)

both will throw a confirmation in some form

Regarding 1# - a change in the right menu. 
Change confirmed by pressing the confirmation button on top. 
Change cancelled by leaving the page / or by pressing delete with empty selection
![ACTIVATE and DEACTIVATE](https://user-images.githubusercontent.com/82385103/172052681-48b66847-1869-425b-ace9-5ae0bf7fbf50.png)

Regarding 2# - confirmation dialog box. 

Also to mention: Both throw on confirmation tasks in the task manager

**Comment by NeoPlays** [comment]
#438 is still pretty basic and starts or stops the service when the red button is clicked and when done it changes the color (green, grey)
