### ISSUE TITLE
Update management with the Chrome extension

### ISSUE THREAD

**Issue by mabasian** [stereum-dev/ethereum-node#367]
Create a small Chrome extension app to update the Stereum 2.0.0 without running the application.

Chrome types must be installed in the project to set the npm for extension building.

```
npm init 

npm i types @types/chrome
```

<h3> Create a manifest.json file to make dependencies</h3>

 It must be built using the Google documentation found in the link below

[manifest](https://developer.chrome.com/docs/extensions/mv3/manifest/)

Besides, the electron API is also present in the link below

[electron api](https://www.electronjs.org/docs/latest/api/extensions#chromedevtoolsinspectedwindow)

**Comment by NeoPlays** [comment]
This is not what we thought it would be. This allows to load crome extension in electron.
