### ISSUE TITLE
Make client choosable on one-click-installer "Staking"

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#371]
Right now the setup chooses the client for the user and the user has no way to change the choice. The user should be able to change the selected client.

**Comment by daGscheid** [comment]
Here is an idea how we could fit this in the current design. 

![ONE CLICK INSTALLATION – CLIENT CHANGE](https://user-images.githubusercontent.com/82385103/173200665-90d6ee95-1254-48c6-aed2-c52499b2edf5.png)

**Comment by stefa2k** [comment]
I like the idea! Can you make it clear to users to be able to change it? It might look to some as all of them get installed or something... Red/Green circles? "Change" button?

However, I'm unsure how stable the validator clients are working with other teams' consensus clients.

**Comment by daGscheid** [comment]
Then we will limit the selection to execution consensus clients. And change the validator clients based on consensus clients. Will talk with Max about it. 

When it comes to the clarity issue. Here is what I would suggest. What do you think? 

![2022-06-13-18-23-55](https://user-images.githubusercontent.com/82385103/173400512-1a7f70a7-7226-4ffa-8cb7-a0da3d1c331a.gif)

(PS: GIF is highly compressed - though looks kinda cool)

**Comment by stefa2k** [comment]
I like it, we just need to make sure to tell the users they can change it somehow. With the tutorial maybe?
