### ISSUE TITLE
Some SSH-key formats are unsupported

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#402]
Some SSH key formats look like causing troubles when using with Stereum Launcher 2.x

**Comment by sapien99** [comment]
do we have samples for non-supported key formats? We use https://github.com/mscdex/ssh2 - all the key formats the lib supports should be also supported by the launcher

**Comment by sapien99** [comment]
Take a look at https://github.com/mscdex/ssh2#client-methods, especially supported kex, formats and ciphers

**Comment by domioiRL** [comment]
The issue we are facing right now is as follows:
We were trying to connect to a server with stereum 2.x with 2 differently generated keys, one was generated by the server host (AWS whatever the default key type is) and the other key was generated by me using `ssh-keygen -m PEM -t rsa` (a format that is supported by stereum 1)
With both added to the `authorized_keys` file ,when trying to connect with stereum we get an error stating that all available authentication methods failed, even though connecting via a terminal with ssh is no problem

**Comment by sapien99** [comment]
do we have an output from the serverside sshd? We should hopefully find there what it compains about

**Comment by sapien99** [comment]
Perfect, thanks! Lets see how we can reproduce and analyze this one

**Comment by stefa2k** [comment]
Works, no action required anymore
