### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#405]
Please fill up https://github.com/stereum-dev/ethereum-node/wiki with technical documentation about Stereum, this includes:

- [x] What technology does Stereum Launcher use?
- [x] How does the login work?
- [x] How are secret data protected?
- [x] How is the Stereum Launcher communicating with the host?
- [x] What technology does the backend on the host use?
- [x] How is the automated firewall working? Rules?
- [x] What host users are used?
- [ ] What's necessarey to integrate a new Plugin (service; e. g. consensus client)?

**Comment by daGscheid** [comment]
Moved outstanding point on this issue into new documentation repo -> https://github.com/stereum-dev/ethereum-node-web-docs/issues/9

Already addressed topics transfered! :)
