### ISSUE TITLE
Visit the website of a plugin via mouse over menu

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#410]
Visit the website of the plugin (e. g. https://github.com/prysmaticlabs/prysm for Prysm plugins), open it in the default os browser

**Comment by daGscheid** [comment]
I found these two we could do: 

Github
GETH - https://github.com/ethereum/go-ethereum
NETHERMIND - https://github.com/NethermindEth/nethermind
HYPERLEGER BESU - https://github.com/hyperledger/besu


PRYSM - https://github.com/prysmaticlabs/prysm
LIGHTHOUSE - https://github.com/sigp/lighthouse
TEKU - https://github.com/ConsenSys/teku
NIMBUS - https://github.com/status-im/nimbus-eth2
LODESTAR - https://github.com/ChainSafe/lodestar

SSV NETWORK - https://github.com/bloxapp/ssv-network

GRAFANA - https://github.com/grafana/grafana
PROMETHEUS - https://github.com/prometheus/prometheus 

alternatively linking to documentation
GETH - https://geth.ethereum.org/docs/  
NETHERMIND - https://docs.nethermind.io/nethermind/  
HYPERLEDGER BESU - https://wiki.hyperledger.org/display/BESU/Hyperledger+Besu  

PRYSM - https://docs.prylabs.network/docs/getting-started/ 
LIGHTHOUSE - https://lighthouse-book.sigmaprime.io/  
NIMBUS - https://nimbus.guide/  
TEKU - https://docs.teku.consensys.net/en/latest/  
LODESTAR - https://chainsafe.github.io/lodestar/  

SSV NETWORK - https://docs.ssv.network/  

GRAFANA - https://grafana.com/docs/grafana/latest/  
PROMETHEUS - https://prometheus.io/docs/introduction/overview/  

What would you prefer @stefa2k?
