### ISSUE TITLE
Buttons in OneClickInstaller are bugged

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#429]
when the cursur is on the button the button changes color and everything is fine:
<img width="202" alt="Bildschirmfoto 2022-06-22 um 13 53 24" src="https://user-images.githubusercontent.com/80448387/175024239-27689398-994e-4388-b7db-3cf47a9418d4.png">

But when you are a litte bit off the button ist still clickable and you get to the next page but the click event for the installation is not triggered:
<img width="189" alt="Bildschirmfoto 2022-06-22 um 13 53 18" src="https://user-images.githubusercontent.com/80448387/175024254-9b34781e-00f7-4600-aad5-807bf3820cc8.png">

Ignore my drawing skills the cursor gets deleted on screenshot ^^

**Comment by maxbehzadi82** [comment]
nice screenshot :)
