### ISSUE TITLE
Starting plugin doesn't work

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#450]
After successfully stopping Grafana it doesn't work to start it again. The on-off button is still red too.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/54934211/175764438-d998bba5-e517-4a73-b0bb-bfe21f1ab74d.png">

**Comment by NeoPlays** [comment]
due to Grafana provisioning the `manage-service` role needs it on every start
couldn't figure it out yet

**Comment by stefa2k** [comment]
Gonna move the whole grafana provisioning to ansible
