### ISSUE TITLE
Lanuage Selection - Clarity

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#468]
I would suggest we should communicate which languages haven't been finished translating yet at latest with the full release. 
I would suggest for this purpose to just simply grey them out 
We could potentially even link the greyed out buttons to the incomplete translation to our website to a page explaining how one could get involved translating it. 

For this purpose, I am currently working on a page that will be found under this address [https://stereum.net/language-program/]

![image](https://user-images.githubusercontent.com/82385103/176704659-02e49c41-cd0c-402a-b800-4ec12b7e83f7.png)

**Comment by maxbehzadi82** [comment]
Would you like to change it to a drop-down?
how many more flags you would add?

**Comment by daGscheid** [comment]
> Would you like to change it to a drop-down? how many more flags you would add?

I like that way, it is displayed, we could make the box bigger. 5 per column and a top and bottom row. 
@maxbehzadi82 consider this, there are currently over 7100 known languages spoken worldwide, and only 23 of them cover half the planet. So the number of languages will be somewhere between 23 and 7100 I guess.
