### ISSUE TITLE
Language Selection - Changing after picking is not possible

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#470]
![image](https://user-images.githubusercontent.com/82385103/176709208-2c8cd544-a1c7-4a13-a1a0-c37a239ea072.png)

Clicking the flag again does nothing. No way back, no room for mistakes 😄 
Should open the language selection menu again, when clicking the flag!

**Comment by maxbehzadi82** [comment]
you have to be careful. Only one chance. :)
I'll take a look.
