### ISSUE TITLE
More Details of Tasks

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#472]
Make subtasks clickable to open a window or something with some room to display more details about a task

**Comment by daGscheid** [comment]
I would suggest a copy button for error (makes your life easier when sharing @NeoPlays)?

**Comment by NeoPlays** [comment]
haha yes like the idea of a copy button 🙌🏼

**Comment by NeoPlays** [comment]
> I would suggest a copy button for errors (or copy by click). Makes your life easier when sharing @NeoPlays)?
> 
> I liked your idea: "making the subtasks clickable which then opens a window with some details"
> 
> Will suggest some paths what this could look like
haha yes like the idea of a copy button 🙌🏼

**Comment by daGscheid** [comment]
Talked with @maxbehzadi82 
- [ ] Add Tooltip to display more information
- [ ] Add Copy Button for Errors

**Comment by NeoPlays** [comment]
implementation from backend needed
