### ISSUE TITLE
Installation Option Selection - Text & Responsiveness Improvements

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#473]
![image](https://user-images.githubusercontent.com/82385103/176710942-8a89f23b-7ce1-456f-9610-932d45cdfa24.png)

3 things.

- [x] The loading bar should turn green when the OS is supported & red when it isn't. 
- [x] As you can see the loading bar misses some responsiveness (rest of page works fine)
- [x] ~~Really Minor: I would also reduce the size of the text in the box ("IN THIS STEP YOU CHOOSE [...]") really minimally. It seems a little packed!~~

**Comment by maxbehzadi82** [comment]
It does look like this in my machine




![Screenshot 2022-07-01 at 12 47 52](https://user-images.githubusercontent.com/69126271/176880780-edcda602-cc5b-47c2-b74f-fc0538dd5982.png)

**Comment by maxbehzadi82** [comment]
Is it the latest version you are running?

**Comment by daGscheid** [comment]
> Is it the latest version you are running?

Yeah, it is the latest on Windows. I would show you on Monday in person if you want to.
