### ISSUE TITLE
Custom services setup

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#498]
Right now it's only possible for the user to install a complete setup like Staking-Node or Blox SSV Operator. Users should be able to:

- [x] #499
- [x] #500
- [x] #501
- [x] #502

@daGscheid please provide some UI draft for this

**Comment by daGscheid** [comment]
I can approach writing everything I have on my mind out in multiple ways, I try to cover as much as possible.

So the basic logic of the pages is the following:
On the node page as well as the control page you are capable of using the services, edit their configuration, start and stop them and update them. 

The "EDIT NODE PAGE" is used to setup the node itself.  This where the custom services magic happens, so entering it, you are greeted with a way to customize the components your node is made out of.  In my example this is empty and we are operating on the "Ethereum mainnet" (we aren't really, but ignore that haha)

![image](https://user-images.githubusercontent.com/82385103/177873339-3e7181db-80b8-4b59-b495-baa019014418.png)

There some basic rules when it comes to custom installation with this page. Making a change to the node is usually confirmed by pressing the giant confirm button on the right side, which will que tasks into the task manager. 

Every change to be confirmed is listed in the que like list on the right. 
Having it sorted is probably a smart idea.

I suggest this basic logic for the custom installation task que (visually at least):  

- REMOVING BEFORE ADDING

- WHEN ADDING:

Execution 
before 
- Consensus
before 
- Validator Client
before 
- services


Basic functionality: 

---

- #500 adding services 

PATH 1# DRAG & DROP 

https://user-images.githubusercontent.com/82385103/178147779-4777b30f-5280-41bc-8815-707a364e6a37.mp4

![image](https://user-images.githubusercontent.com/82385103/178070318-3c87b674-02bd-4ac1-a423-53a94aabe451.png)


PATH 2# CHOOSE FROM LIST
![image](https://user-images.githubusercontent.com/82385103/178147756-8898332c-b9de-44a2-a56e-31a247e91883.png)

The current display being changed in the Node Edit Tab to present all choices for the category to add to the Node 

![image](https://user-images.githubusercontent.com/82385103/178147819-66ac1a02-df79-493d-98f5-637da716d2b9.png)

MENTIONS: 
- [ ] Selected to install items (but not yet installed) should have around 30% transparency
- [ ] To remove a selected item from the custom installation que just drag it into the delete section / trash can or click the item on the custom installation task que on the right. (To remove an installed service refer to #502 explanation on this page)


----

- #502 removing services

https://user-images.githubusercontent.com/82385103/178148597-d5f1b4a0-15cd-4123-a018-c1a6a2c96b3c.mp4

There is only one path currently to remove. It is by clicking the item in the middle and then clicking remove. While I would like to keep this way generally - clicking once selecting service - using this logic for #501 (a little below)
We should build the custom installation up to be also capable of using drag and drop. Dropping the items from the middle onto the trash can icon or at least onto the task que. 

----  

- #501 modify services

Currently I would like to tackle #501 in combination with a similar UI solution present in #407. 

FOR REFERENCE (solution currently worked on for #407)
![image](https://user-images.githubusercontent.com/82385103/178148855-35fc57d0-9c89-4f39-a378-a9fb5ca7dc88.png)

How this looks like exactly I will follow up with when I get better grasp on how we can present the changes made to node and when editing them will/can take effect.
