### ISSUE TITLE
Switch network

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#503]
If the server is using one set of compatible networks (e. g. for testnet goerli & prater) then the user can switch network. If the user decides to do so, Stereum needs to:
- [ ] support mainnet for el/cl
- [ ] create same services with same configuration on the newly selected network
- [ ] uninstall services on the old network (also see #502 )
- [ ] startup new services

@daGscheid please provide UI draft for this

**Comment by stefa2k** [comment]
I like the idea of showing the network, but we shouldn't restrict the user to only run one network on a server. It should be possible to run on multiple networks on one server.

How about tabs/switch/whatever to switch the displayed network and its plugins?

**Comment by daGscheid** [comment]
> How about tabs/switch/whatever to switch the displayed network and its plugins?

To address this we could combine this and what I mentioned in #268 into one solution. Basically when first setting up a node, you set up one node on your server.  When clicking the Stereum Icon Left Top, you can set up an additional config and we could use the following pic to switch configuration and repurpose, most of the UI design of #268.

![EN - NODE TAB - HOME –  INSTALLED – 1](https://user-images.githubusercontent.com/82385103/177984763-7b11a741-4c78-4953-a031-6c61c240829d.png)

We could later even build this up to easier switch between saved server connections (-> #268 leading to login) if we bundle it well, we can keep the necessary amount sites at a minimum.

**Comment by daGscheid** [comment]
> How about tabs/switch/whatever to switch the displayed network and its plugins?
-----
As mentioned in the last sentence, we could turn the network display into a drop down menu. Would certainly fit better, we could remove a button, however could lead to confusion in the node tab - when it is simple a display - but we can address this with color. I would like to know how it feels first, maybe a simple confirmation dialog box after switching would simply feel better. When it comes to the right menu for #498 it would be necessary to add anyway.


 REGARDING MY LAST COMMENT: 


> > I like the idea of showing the network, but we shouldn't restrict the user to only run one network on a server. It should be possible to run on multiple networks on one server.
> 
> To address this we could combine this and what I mentioned in #268 into one solution. Basically when first setting up a node, you set up one node on your server. When clicking the Stereum Icon Left Top, you can set up an additional config and we could use the following pic to switch configuration and repurpose, most of the UI design of #268.
> 
> ![EN - NODE TAB - HOME – INSTALLED – 1](https://user-images.githubusercontent.com/82385103/177984763-7b11a741-4c78-4953-a031-6c61c240829d.png)
> 
> We could later even build this up to easier switch between saved server connections (-> #268 leading to login) if we bundle it well and make same server node configs a kind off drop down when logged-in. Being able to choose between adding a login or set up a new node config when pressing plus. That way we can keep the necessary amount sites at a minimum.

**Comment by stefa2k** [comment]
There are a couple of things to keep in mind:
- one should not run a mainnet staking/dapp/rpl/ssv node with testnet services on the same node for security reason
- mixing up "node" and "network-setup" is dangerous if not lined out well to the user
- "change network" to migrate would be pretty intuitive with this (again: if properly explained to user)

Let's talk monday

**Comment by stefa2k** [comment]
added `support mainnet for el/cl` as task

**Comment by daGscheid** [comment]
> Include Checkpoint Sync for Consensus Clients
