### ISSUE TITLE
Switch out execution/consensus client

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#504]
The user can choose to switch out an execution or consensus client. This means the old client get's uninstalled and the new client installed.

User needs to enter:
- new compatible client
- data paths
- sync source (for execution / consensus client) 

Process:
- [ ] create the new service, use the user input and apply same connectivity as the old service
- [ ] uninstall the old service (see #502 )
- [ ] startup new service

@daGscheid please draft some UI for this

**Comment by daGscheid** [comment]
-> Includes Sync Source Selection UI
