### ISSUE TITLE
Integrate flashbots mev-boost

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#529]
Integrate with each client:
- [x] Lighthouse (see https://github.com/flashbots/mev-boost/issues/160 )
- [x] Nimbus (see https://github.com/flashbots/mev-boost/issues/159 )
- [x] Prysm (see https://github.com/flashbots/mev-boost/issues/158 - https://hackmd.io/@prysmaticlabs/BJeinxFsq )
- [x] Teku (see https://github.com/flashbots/mev-boost/issues/156 )

Additional services:
- [ ] relay
- [ ] block producer

Useful links:
- https://writings.flashbots.net/writings/mev-boost-call-for-testing/
- https://flashbots.notion.site/MEV-Boost-Status-Update-July-1-15-2022-759ca682f96e45848e874ce1195b8dea

**Comment by stefa2k** [comment]
Due to implemented censorhip in flashbots' mev-boost, please don't merge anything to `main` branch (PR draft is fine of course!). We need to wait how this turns out: https://github.com/flashbots/rpc-endpoint/pull/92

**Comment by stefa2k** [comment]
Please check implementation with this: https://github.com/remyroy/ethstaker/blob/main/prepare-for-the-merge.md#configure-your-consensus-and-validator-client-to-use-mev-boost

**Comment by gbayasgalan** [comment]
> Please check implementation with this: https://github.com/remyroy/ethstaker/blob/main/prepare-for-the-merge.md#configure-your-consensus-and-validator-client-to-use-mev-boost

so far it looks good 😀

**Comment by daGscheid** [comment]
Interesting at latest when the UI comes into play.
This website lists all current relays in action.  
https://www.mevboost.org/

**Comment by daGscheid** [comment]
UI Design & necessary steps for completed MEV Boost Integration @maxbehzadi82 & @NeoPlays 

[ ]**CUSTOM INSTALLATION**: MEV BOOST is a service that connects with your CONSENSUS CLIENT / VALIDATOR CLIENT (for CUSTOM INSTALLATION (@gbayasgalan is this correct?)

[ ]**ONE CLICK INSTALLER**:  MEV BOOST will be an additional option in the one click installer. 

When installing: 
It will be of the service category. For ease & because multiple relays are potentially selectable, we could go two paths: 

1# A SERVICE MODAL FOR MEV BOOST




2# A NEW ELEMENT IN THE SETTINGS



(will edit & add UI as soon as I took screenshots tomorrow - it is kind off late haha)

**Comment by gbayasgalan** [comment]
> UI Design & necessary steps for completed MEV Boost Integration @maxbehzadi82 & @NeoPlays
> 
> * [ ]  **CUSTOM INSTALLATION**: MEV BOOST is a service that connects with your CONSENSUS CLIENT / VALIDATOR CLIENT (for CUSTOM INSTALLATION (@gbayasgalan is this correct?)
> * [ ]  **ONE CLICK INSTALLER**:  MEV BOOST will be an additional option in the one click installer.
> 
> When installing: It will be of the service category. For ease & because multiple relays are potentially selectable, we could go two paths:
> 
> 1# A SERVICE MODAL FOR MEV BOOST
> 
> 2# A NEW ELEMENT IN THE SETTINGS
> 
> **_(will edit & add UI as soon as I took screenshots tomorrow - it is kind off late haha)_**

Yes, you're right. 
Note: some services (teku & nimbus) haven't separate services, while other CLs run beacon & validator services separately.

**Comment by daGscheid** [comment]
> ![MEV BOOST](https://user-images.githubusercontent.com/82385103/194708120-8f3f00c2-fb92-4c69-828d-7bf113fc99a8.png)
> 
> ![MEV BOOST-1](https://user-images.githubusercontent.com/82385103/194708126-e59408e1-4041-4707-8c1b-54edc4010bb6.png)
> 
> ![MEV BOOST-2](https://user-images.githubusercontent.com/82385103/194708127-2ab9c837-ba82-48fb-abce-4f5954243745.png)
> 
> ![MEV BOOST – 1](https://user-images.githubusercontent.com/82385103/194708135-1ee398c3-392d-4291-a8cf-d3e8c5d4b06e.png)

@gbayasgalan If I select multiple, are they to be understood to be sortable by priority?  How does it decide which one it would pick if select multiple relays? Do we have to make them sortable in some way? (up/down in list?)

**Comment by stefa2k** [comment]
> @gbayasgalan If I select multiple, are they to be understood to be sortable by priority? How does it decide which one it would pick if select multiple relays? Do we have to make them sortable in some way? (up/down in list?)
There is no priority of the relays when specified for flashbots mev-boost. Flashbots decides according to rewards which of the blocks of the relays to choose.
