### ISSUE TITLE
List of All Ports in Use

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#535]
Offer an UI element that shows all ports in use.

**Comment by daGscheid** [comment]
Currently there is no way to see all used ports in Stereum. To use some of the space free space we have in the dashboard, I propose a solution that will look something like this: 
![PORT LIST](https://user-images.githubusercontent.com/82385103/198014052-858ab036-439d-4618-a0d3-bb131da310ab.png)


Like the storage dashboard cards it should be scrollable.

**Comment by daGscheid** [comment]
there are 3 different port categories:
container ports
- useful only for Stereum services
- not able to connect to them from outside the server
- no need to show them imo

public container ports
- ports of a container bound to a network interface 
- port of container and port on network interface can differ, network interface can differ too
- find them in expert mode -> ports:
- used to make p2p (el/cl) easier for services or make services available to the host and forward them via ssh tunnel ports (Prometheus for widgets, ...)

ssh tunnel ports
- there needs to be an ssh tunnel from the local pc (desktop with stereum launcher) and the node (stereum node)
- e. g. rpc-connection
- not accessible by anyone outside of your pc or server
- used to connect to Grafana, Prometheus, RPC-Endpoints, ...

----

We will show the "Public Container Ports" in the Component. For this will adapt it to look like this

**Comment by NeoPlays** [comment]
@daverolo this is done right?
If so could you connect your pr to this issue and close it
