### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#552]
Things to update:
- OS
- Roles
- Services
- Launcher https://www.electronjs.org/de/docs/latest/api/auto-updater

Update the host `configure-updates`
to continue after updating the OS with reboot see
- https://www.reddit.com/r/ansible/comments/e8f0lf/comment/fabhsvv/?utm_source=share&utm_medium=web2x&context=3
- https://github.com/latchee/Ansible/blob/main/Archive/update-ansible-initialisation.yml
- https://github.com/latchee/Ansible/blob/main/Archive/update-ansible-finalisation.yml

**Comment by daGscheid** [comment]
Can be activated / deactivated in the Stereum settings - accessible by clicking the gear icon in the top bar. 
selection will be displayed via #677 in the Update Model 

Reference: 
![image](https://user-images.githubusercontent.com/82385103/187448068-ecfb5649-804f-4d50-a0e1-d04504cd78c2.png)

**Comment by NeoPlays** [comment]
For launcher updates i found the following:
If your app is packaged with electron-builder, you may not need this module. Builder has its own built-in mechanism for updating apps. Find out more at [electron.build/auto-update](https://www.electron.build/auto-update).

**Comment by stefa2k** [comment]
Just for documentation:
### Update Stereum
![image](https://user-images.githubusercontent.com/54934211/190167114-945d0b0d-2fa1-40c1-91a0-ae79b1cf2f44.png)
This runs:
- `update-stereum`
- `update-changes`

### "UPDATE ALL"
![image](https://user-images.githubusercontent.com/54934211/190167670-3df34810-08dd-4e93-8923-f4be82474ddd.png)
This runs:
- `update-stereum`
- `update-changes`
- `update-services` (no params -> all services get updated)
