### ISSUE TITLE
Stereum Mobile App integration

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#563]
The mobile app "Stereum Node Monitor" is already available for [iOS](https://apps.apple.com/at/app/stereum-node-monitor/id1605910573?l=en) and [Android](https://play.google.com/store/apps/details?id=cloud.stereum.monitor&gl=AT) and used in Stereum 1.

Stereum node needs to support one additional service: https://hub.docker.com/r/stereum/notifications
A configuration example of the service in `docker-compose`: https://github.com/stereum-dev/ethereum2-docker-compose/blob/prater/compose-examples/lighthouse-only/override-examples/docker-compose.notifications.override.yaml#L20

Also Grafana needs additional configuration: https://github.com/stereum-dev/ethereum2-docker-compose/blob/prater/config/grafana/provisioning-lh/notifiers/notifier.yaml

The service generates a qr code which includes the push notification id as well as the encryption key. The Stereum Launcher needs to show this qr code in the settings/config.

Tasks:
- [x] Integration in Stereum node ansible backend + molecule test
- [x] Integration in Stereum Launcher (after #498 is done)
- [x] add to update metadata

**Comment by daGscheid** [comment]
Should follow the work for #571 to maybe offer some pre configured alerts, I would like to change the Notification Page to navigate to something like this. 

I don't know if there is a possibility have access to option to configuring alerts in Stereum itself, if so I would like to make it possible to at least clear the list of pre configured alerts. Adding them could be done in Grafana

![Notifications](https://user-images.githubusercontent.com/82385103/200191433-bb914339-a087-4e49-b5df-a598be98b386.png)

A list of connected services on the right side would be nice - here you can also quickly access the menu to connect them by clicking the options. 

For this issue relevant is especially: 
![NOTIFICATIONS STEREUM MONITOR](https://user-images.githubusercontent.com/82385103/200191399-a66e4702-ba37-4247-843b-fefc39700224.png)
