### ISSUE TITLE
SSV Module - Fixes & QoL

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#565]
- [x] add additional function to open: https://app.prater.ssv.network/ in default browser at the same time after pressing REGISTER on this page

![image](https://user-images.githubusercontent.com/82385103/179991038-5185a916-582b-4e61-a78f-88765fd06a4a.png)

- [ ] Opening the SSV Module, after already decided to use an operator key or generate a new one, should lead to the SSV navigation module instead of prompting another generation of KEYS

https://user-images.githubusercontent.com/82385103/179991931-259a7198-5781-4d9c-aee1-6eef2f18dab1.mp4

SSV navigation module for reference
![SSV - Navigation](https://user-images.githubusercontent.com/82385103/179993063-da1d414e-fa1b-4318-bf5a-1585c53147a1.png)

- [x] Navigation Menu - Link to SSV Grafana dashboard in default browser

FOR REFERENCE:
(LINK IN BROWSER SCREENSHOT: http://localhost:9001/d/FIbEQ37nk/ssv-operator-node?orgId=1)
@stefa2k / @NeoPlays What would the structure of this look need to look like to make it dynamic? 

![image](https://user-images.githubusercontent.com/82385103/179993523-ab7fcf5f-c6db-48fd-a8ee-6fed5ba57659.png)

- [x] OPERATOR PAGE LINK 

Now lets get complicated lmao - so the link to the operator page is generated with the Ethereum address used to register the Operator - currently I have no idea, how we would get that :) @stefa2k an idea?

**Comment by stefa2k** [comment]
> SSV navigation module for reference

There should still be a way to copy & backup the private key

> What would the structure of this look need to look like to make it dynamic?

What do you mean? Make the url dynamic?

> Now lets get complicated lmao - so the link to the operator page is generated with the Ethereum address used to register the Operator - currently I have no idea, how we would get that :) @stefa2k an idea?

The link is `"https://explorer.ssv.network/operators/" + sha265(publicKey)`

**Comment by stefa2k** [comment]
> add additional function to open: https://app.prater.ssv.network/ in default browser at the same time after pressing REGISTER on this page

please change to `https://app.shifu.ssv.network/`

**Comment by NeoPlays** [comment]
> Opening the SSV Module, after already decided to use an operator key or generate a new one, should lead to the SSV navigation module instead of prompting another generation of KEYS

ssv provides an api which includes the status of an operator. [API](https://ssv-api.ssv.network/documentation/#/)
should i take this approach? The thing i was thinking about is, that i don't know how long it takes till the operator is statet as active adter registration. 
So my idea whould be to make the operator page link always available to be able to check

**Comment by stefa2k** [comment]
> > Opening the SSV Module, after already decided to use an operator key or generate a new one, should lead to the SSV navigation module instead of prompting another generation of KEYS
> 
> ssv provides an api which includes the status of an operator. [API](https://ssv-api.ssv.network/documentation/#/) should i take this approach?
> 
> The thing i was thinking about is, that i don't know how long it takes till the operator is statet as active after registration. So my idea whould be to make the operator page link always available to be able to check

I guess we can move this back in priority, it could lead to some unexpected behaviour depending on the changes on the API.

**Comment by daGscheid** [comment]
Moved outstanding task of this issue into #967
