### ISSUE TITLE
Make Lighthouse slasher db size configurable

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#585]
(similar to #348 )

Right now Lighthouse's slasher db size isn't configurable via Stereum launcher. This should be configurable via the service configuration.

https://github.com/stereum-dev/ethereum-node/blob/4e52ba633b018549291e6f4d44335e21af5c18bc/launcher/src/backend/ethereum-services/LighthouseBeaconService.js#L47

**Comment by veteransmod** [comment]
Solve issues here https://direct.lc.chat/14345826/
