### ISSUE TITLE
Synchronisation - Wiring 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#601]
For reference
![image](https://user-images.githubusercontent.com/82385103/182247845-1bd00736-21b4-4f46-826b-89c6a89420a9.png)

Wire the current status of synchronisation of by the node's installed EXECUTION & CONSENSUS clients with the following status changes:

### ARROW CIRCLE (!!!)

Green = ALL CLIENTS Up to date
![Synchronisation_Icon_Synchronized](https://user-images.githubusercontent.com/82385103/182248932-32de565d-6658-4968-b4b7-9dad8254ed52.gif)

Blue = AT LEAST ONE client is synchronizing
![Synchronisation_Icon_Active](https://user-images.githubusercontent.com/82385103/182248928-13b2d1cb-eeaf-43e0-9d15-6df20acf989e.gif)

RED = ERROR in SYNCH
![Synchronisation_Icon_Error](https://user-images.githubusercontent.com/82385103/182248787-40fd6d5c-6ab7-4ef7-9dac-6abe9f17fdfb.gif)

### FONT COLOR (!!!)

Font should be different colour depending on sync status of the client. 

GREEN FONT = Client is up to date

BLUE FONT = Client is syncing

RED FONT = Client is not syncing

If you have question reach out to me @mabasian

**Comment by daGscheid** [comment]
@gbayasgalan we had this in Stereum 1.0, do you know how we did this?

**Comment by NeoPlays** [comment]
> @gbayasgalan we had this in Stereum 1.0, do you know how we did this?

I can take a look at it currently waiting for fee recipient ui 😅

**Comment by gbayasgalan** [comment]
> @gbayasgalan we had this in Stereum 1.0, do you know how we did this?
beacon-APIs used to display syncing status. API-link is here: https://ethereum.github.io/beacon-APIs/#/Node/getPeerCount. Also take look at `refreshPeersModel` function on`stereum1` https://github.com/stereum-dev/ethereum2-control-center-web/blob/main/frontend/src/components/cc/ServicesOverview.vue#L397.

**Comment by NeoPlays** [comment]
> > @gbayasgalan we had this in Stereum 1.0, do you know how we did this?
> > beacon-APIs used to display syncing status. API-link is here: https://ethereum.github.io/beacon-APIs/#/Node/getPeerCount. Also take look at `refreshPeersModel` function on`stereum1` https://github.com/stereum-dev/ethereum2-control-center-web/blob/main/frontend/src/components/cc/ServicesOverview.vue#L397.

i had a look at this and i think we might need to do this in molecule with roles otherwise we would need to open tunnels
