### ISSUE TITLE
VALIDATOR KEY COMMANDS - simple - COPY / GRAFFITI / REMOVE KEY(s) / EXIT CHAIN

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#612]
Validator Key Commands 

Copy Key Button
- [x] Copy Public Key of individual key

> It is a copy function for the public operator key (pic for reference), maybe accompanied by a small popup? I will let you decide Max :) 
>
> ![copy](https://user-images.githubusercontent.com/82385103/185242844-f972f8ad-b780-41b9-8e9b-1228c523df14.png)
>

-> #317 [change GRAFFITI ](https://github.com/stereum-dev/ethereum-node/issues/317)
@maxbehzadi82 needs additional UI (similar to FEE RECIPIENT)
- [x] overwrite Graffiti for all Keys (right menu)
- [x] overwrite Graffiti for individual key (not possible through validator key api)

-> #674 REMOVE KEY
removes keys from validator client (Produces Task, removes key in backend/UI)
- [x] remove all keys (right menu)
- [x] remove individual key

-> #678 EXIT CHAIN 
exits the chain with the validator keys 
@maxbehzadi82 **needs fat warning and extra confirmation** (check box?)
- [x] exit chain with all keys (right menu)
- [ ] exit chain with individual key

**Comment by NeoPlays** [comment]
>  #678 EXIT CHAIN exits the chain with the validator keys @maxbehzadi82 **needs fat warning and extra confirmation** (check box?)

Is this a so called `voluntary exit` @stefa2k

**Comment by daGscheid** [comment]
> > #678 EXIT CHAIN exits the chain with the validator keys @maxbehzadi82 **needs fat warning and extra confirmation** (check box?)
> 
> Is this a so called `voluntary exit`? @stefa2k

Yeah it is.

**Comment by daGscheid** [comment]
Exit Chain handled in #944
