### ISSUE TITLE
Support checkpoint sync

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#624]
Right now syncing takes a long time, especially on mainnet. Until we are able to integrate [SyncLink](https://github.com/stereum-dev/synclink-spec) please provide the possibility of checkpoint sync.

Users need to enter their infura.io (or any similar service) url in order to perform a checkpoint sync of the consensus clients. This input occures at:
- OneClickInstallation
- Adding a new consensus client #500 
- Switching network #503 
- Switching consensus client #504 

Clients:
- [x] Lighthouse `--checkpoint-sync-url "http://remote-bn:5052"`
- [x] Nimbus `--trusted-node-url=http://localhost:5052`
- [x] Prysm `--checkpoint-sync-url http://other-node:5051`
- [x] Teku `--initial-state=http://other-node:5051/eth/v2/debug/beacon/states/finalized`

@daGscheid please provide the UI for this!

**Comment by daGscheid** [comment]
Here is the current plan for all 4 cases. Most of it is with the thought in mind that it can later be reused for Execution Clients & include SyncLink as an option. 

CASE 1# One Click Installation 

We drop FastSync & use the space to include an additional element to specify an URL. The user can select between Genesis Sync or Checkpoint Sync. 
![ONE CLICK INSTALLATION](https://user-images.githubusercontent.com/82385103/184137149-e2e31cfc-8306-487f-bac9-5f466206840d.png)
![ONE CLICK INSTALLATION – 1](https://user-images.githubusercontent.com/82385103/184137153-25eacf68-7f83-4372-b5bd-4be56a9d134e.png)

This solution will be also part of 2# for every Consensus Clients as soon as we reach the custom installations full implementation: 
f.e. Prysm
![CUSTOM INSTALLATION](https://user-images.githubusercontent.com/82385103/184137336-69d5aa94-8719-4ad3-a4af-24dc959d5042.png)


CASE 3#: NETWORK SWITCH
Pressing the button to switch the network adds an additional step to define the sync source...
![image](https://user-images.githubusercontent.com/82385103/184144729-adb4ba87-fe13-4b89-9729-2d8ae03e13e9.png)

....looking like this. We add an additional step to both execution & consensus client to define their sync source (the execution client just doesn't have a second option) 


![NETWORK SWITCH](https://user-images.githubusercontent.com/82385103/184145185-df2313bc-953a-4649-9956-ce1c80be94d6.png)

After confirming your selection is taken. 


CASE 4# will be addressed similiarish to case 3#. An specific UI will follow for this. 

CASE 5#: An additional case, I propose: You just want to re-sync for some reason (f.e. smth is not working right)

in the settings there will the option for you to click (for Consensus & Execution client) to delete your chain data & inniate a re-sync. With this element you are also able to chose the source. 

![PLUGIN SETTINGS – 1](https://user-images.githubusercontent.com/82385103/184145480-d3f3039f-fec3-432a-abb2-77340db49f9d.png)
