### ISSUE TITLE
Show service version

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#625]
Right now users need to look into the configuration in Expert Mode to find out about the current version:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/54934211/183252730-bd7210c0-94f9-4d4e-8fc5-19abc6b5e01e.png">

It would be good to have this information either also somewhere on this modal window and/or on the control page at the Plugin information:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/54934211/183252772-5d592605-3e06-4264-a8e8-87e05d2ca5d9.png">

**Comment by maxbehzadi82** [comment]
I think the right side of the footer would be a good place. The version will always be displayed on all pages.

**Comment by daGscheid** [comment]
> I think the right side of the footer would be a good place. The version will always be displayed on all pages.

![version](https://user-images.githubusercontent.com/82385103/183261404-2bdf83f9-7d43-4bad-be20-1b73e75714ca.png)

Do you mean here?  
Do we ever use the left side of the footer in the modal? 

![version](https://user-images.githubusercontent.com/82385103/183261605-519b75e6-d862-4208-9464-7b452ff7ebf7.png)

Would put it somewhere here, IF we don't use the space

---> still thinking about control page. Would need some changes to fit it OR we change some info on click? @maxbehzadi82

**Comment by daGscheid** [comment]
One the Control Page
![image](https://user-images.githubusercontent.com/82385103/183262686-df146878-dfcb-4994-bc94-372d600725b8.png)

@maxbehzadi82 Just an Idea click, adding small icon ( C / id / ver), clicking it changing the displayed info on the component

![image](https://user-images.githubusercontent.com/82385103/183262972-394c716a-61d8-4e73-8534-ddc8c77c9bb5.png)

f.e.

       from 

Plug-In Name 
Client Category 

         to

Plug-In Name 
Version
         
         to

Plug-In Name 
ID


So you can look up all three things on this page ✌️

**Comment by stefa2k** [comment]
> @maxbehzadi82 Just an Idea click, adding small icon ( C / id / ver), clicking it changing the displayed info on the component

I fear this is not intuitive.

**Comment by daGscheid** [comment]
Currently we show this in the client settings. With this I would consider this done.
