### ISSUE TITLE
Import the slashing db with the validator account keys

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#629]
Please implement the ability to provide a slashing database when importing validator account keys:

- [ ] Lighthouse https://lighthouse-book.sigmaprime.io/slashing-protection.html
- [ ] Nimbus https://nimbus.guide/keymanager-api.html
- [ ] Prysm https://docs.prylabs.network/docs/wallet/slashing-protection
- [ ] Teku https://docs.teku.consensys.net/en/latest/Concepts/Slashing-Protection/
- [ ] Lodestar https://chainsafe.github.io/lodestar/reference/cli/#validator-slashing-protection

**Comment by daGscheid** [comment]
In combination with #631, currently working on a way to import the slashing database. 

In contention:
- import in validator client settings 
- import in Staking page after selecting validator client & before putting in validator key password

**Comment by daGscheid** [comment]
@maxbehzadi82 after having talked with you yesterday. 

For the Validator key Import we will add an additional. It is to be added **after** having **selected the validator keys** to import and **before selecting the validator client** to import to

A element like this will probably serve the functionality well. The user is able to choose no database.  
![FLOW - VALIDATOR IMPORT – 8](https://user-images.githubusercontent.com/82385103/200802050-54a007f1-0053-41cd-8440-46f977348672.png)
