### ISSUE TITLE
Various checks when importing validator account keys

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#630]
Before importing a validator account key there should be certain checks to ensure no slashing can occure:
- [x] Look on beaconcha.in if the validator account key is offline for the last 2 epochs
- [x] Look up if there is a slashing protection file provided #629 

Notify the user about any failed checks. The user can still import when confirming about the failed checks.

**Comment by daGscheid** [comment]
// change plans to get Data from Beacon API
