### ISSUE TITLE
Export the slashing database

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#631]
Each validator client can export a slashing database to ensure a safe migration of the validator account keys. Please provide a way to export the slashing database for the following clients:
- [ ] Lighthouse
- [ ] Nimbus
- [ ] Prysm
- [ ] Teku
- [ ] Lodestar

**Comment by daGscheid** [comment]
For this we currently have a button in the validator client settings discussed. 
![SERVICE_SETTING_MODULE](https://user-images.githubusercontent.com/82385103/198003741-59dff79b-3944-41f0-b0d6-a5ea31f9cd87.png)

Pressing this button opens up a Path Selector to save the database. 
![image](https://user-images.githubusercontent.com/82385103/198004006-d9bc943b-c0ef-417c-af69-07cb0a5924ff.png)
