### ISSUE TITLE
ssv.network adaptions

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#636]
Please take care of the following tasks:
- [x] Guide to setup ssv.network with Stereum (includes: ssh key management, Hetzner, AWS, registering on ssv.network)
- [x] Rename "Blox SSV" to "ssv.network" everywhere on the application and website

After finishing this, please:

- [x] Write an update on the grant proposal thread on their forums

**Comment by daGscheid** [comment]
Closed with writing the update to be found here: https://forum.ssv.network/t/stereum-integration/73
