### ISSUE TITLE
Staking page: no data of beaconcha.in breaks list

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#637]
When beaconcha.in is having issues serving requests for whatever reason, there is no way to see what validator accounts are running. It would be helpful to at least see the public keys and no data for the rest of the table.

**Comment by NeoPlays** [comment]
this is actually a bug can you show me how to reproduce 😅
there is a try catch block to catch any errors which then displays key + service
and there is also an else block which is triggered when the information of the api was successfull but is empty which then also displays key + service

**Comment by stefa2k** [comment]
I guess you could block the access to prater.beaconcha.in somehow on your OS, waiting for an outage wouldn't be feasible I guess.

I think the request just takes very long and runs to a timeout. Maybe the solution could be to display the information as soon as you receive the keys from the beacon api and then enrich them later on with beaconcha.in data?
