### ISSUE TITLE
appImage does not launch due to missing dependency in Ubuntu 22.04

### ISSUE THREAD

**Issue by JamesCarnley** [stereum-dev/ethereum-node#646]
I'm trying to install Stereum 2.0 on a fresh Ubuntu 22.04 LTS instance. I downloaded the Linux install file from stereum.net, marked it as executable, and tried running it:

```
$ ./Stereum-Launcher-2.0.0-stack-rc4.AppImage
/tmp/.mount_StereuEhlQS4/stereum-launcher: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

Are there dependencies that need to be installed first? I couldn't find any notes on this.

**Comment by sapien99** [comment]
Will setup a vm with a ubuntu 22-04 desktop and try myself. I heard about electron not providing libnss some years ago, but lets find out.

**Comment by sapien99** [comment]
On my ubuntu 22.04 desktop release libnss is present. 

![image](https://user-images.githubusercontent.com/1465890/184526596-eedb675c-8bda-4503-8999-8bbefc910f13.png)

As our AppImage requires libfuse2 and ubuntu dropped it and switched to fuse2 i had to install libfuse2 manually:

```
apt-add-repository universe
apt-get install libfuse2
```

Did you maybe use a ubuntu server for the graphical installer, not ubuntu desktop?

**Comment by JamesCarnley** [comment]
Hmm, you're right, sorry. This is a server version. I was assuming I could install Stereum and then connect to it via a browser.

Is it possible to install Stereum via command line?

**Comment by sapien99** [comment]
In principle it should be possible (basically the stereum launcher does excactly that - make you choose your options and then install stereum on a server), but do we have an explicit commandline installer @stefa2k ?

**Comment by stefa2k** [comment]
> Is it possible to install Stereum via command line?

Theoretically yes, practically no. With Stereum version 2 there are way more commands ran directly by the Launcher. Electron is basically a small web browser and a web app. The launcher connects via SSH and runs all the commands for you, also provides you with SSH tunnels to access Grafana, etc.

**Comment by JamesCarnley** [comment]
Hmm. It seems like the guts of Stereum running on a headless machine and the Web UI running on a Windows desktop or phone are nearly supported by the architecture and perhaps also a use case Stereum would like to support as it would be a good UX for users and make future enterprise support easier to add. Functionality-wise everything seems like it would work fine.

Is this something that might be worked on? I can close this issue if not or leave it open to track it over time.

**Comment by stefa2k** [comment]
That's already the case, the web UI runs in Electron.

**Comment by JamesCarnley** [comment]
I fundamentally misunderstood how Stereum works, sorry.
