### ISSUE TITLE
Non Default SSH Port Support

### ISSUE THREAD

**Issue by NeoPlays** [stereum-dev/ethereum-node#650]
Stereum 2 only supports port 22 atm.
The js backend supports the option for another port and is integrated to some point.
One thing missing is some Input on the Login Page for the port.

**Comment by stefa2k** [comment]
Please also save the port to the launcher's config. Right now it doesn't contain the port number:
```
			{
				"name": "test2",
				"host": "2.3.4.5",
				"user": "deployyyy",
				"keylocation": "",
				"useAuthKey": true
			},
```

**Comment by CosmiCloud** [comment]
On the login page you could just allow the user to specify the port they want by using : after the IP.

**Comment by pepawel** [comment]
If for some reason you can't or don't want to change SSH port, you could use port forwarding **on your local machine** as a workaround.

There are many possibilities, personally I use [socat](http://www.dest-unreach.org/socat/) which is an easy to install package in many Linux distributions.
Run this command on your local machine replacing HOST and PORT with address and ssh port of the machine you would like to connect to:
`$ sudo socat -dd TCP4-LISTEN:22,fork TCP:HOST:PORT`

Then configure Stereum to connect to localhost.

Socat works on UNIX, so there is macOS version. I've also found unofficial build for Windows.
