### ISSUE TITLE
Task Manager opens up when changing the page

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#671]
When I change to Control, Node, Staking, everytime the task manager pops up.

@daGscheid do we have some rules on when the task manager shows up on it's own?

**Comment by daGscheid** [comment]
We added a rule, that it opens up after installation, right @maxbehzadi82 ?

**Comment by maxbehzadi82** [comment]
Right.If the services are already installed,after log in routing redirects to the node page.

**Comment by maxbehzadi82** [comment]
Only 10s then will be close.
It was temporary solution.I will make it only for node page after installing.
