### ISSUE TITLE
Disable buttons after click

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#676]
After clicking on buttons they don't get disabled, leading to issues like race-conditions when double-clicking.

All buttons should disable after a single click until the action is reasonable to execute again by the user.

**Comment by maxbehzadi82** [comment]
Most of the buttons on the Stereum are routing to another page with one click.
Do you have any example of which button event should I make once?

**Comment by stefa2k** [comment]
Buttons to update, start/stop

**Comment by maxbehzadi82** [comment]
Aha, sure.
