### ISSUE TITLE
Staking Page - Exit Chain Command - Implementation

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#678]
- [ ] exit chain with all keys (right menu)

### INITIATION
![image](https://user-images.githubusercontent.com/82385103/185384338-4df5cb38-e0ae-4bbe-9740-c84c0bca3baa.png)

### FLOW
![VALIDATOR EXIT-1](https://user-images.githubusercontent.com/82385103/185387929-a0a7f25e-176e-49f7-8252-e5a1e01142bf.png)

![VALIDATOR EXIT-2](https://user-images.githubusercontent.com/82385103/185387055-d6b8e731-6d5d-4663-b919-ade7bb3cf80b.png)

(PUT IN VALIDATOR PASSWORD)
![EXIT CHAIN (2)](https://user-images.githubusercontent.com/82385103/185663963-c3c5b5b7-a22d-4c04-90a4-4c5d140c047f.png)

![VALIDATOR EXIT-3](https://user-images.githubusercontent.com/82385103/185387036-7383c44f-07d8-4e8e-b9c7-e7a51a80312b.png)

![VALIDATOR EXIT-3](https://user-images.githubusercontent.com/82385103/185387675-96847449-b1bb-4a14-b0bd-a46073e88004.png)

<br>
<br>
<br>

- [x] exit chain with individual key 

### INITIATION
![image](https://user-images.githubusercontent.com/82385103/185384409-c06b01ba-40d9-4449-9b51-36b73f7c22c0.png)

### FLOW
![VALIDATOR EXIT – 1](https://user-images.githubusercontent.com/82385103/185387006-9a0ef96a-d1cb-4a1c-a181-4c1c6ed79b1e.png)

![VALIDATOR EXIT – 2](https://user-images.githubusercontent.com/82385103/185387077-9f3f0a97-7700-4da4-a147-8e19014e41bb.png)

(PUT IN VALIDATOR PASSWORD)
![EXIT CHAIN (1)](https://user-images.githubusercontent.com/82385103/185664030-3896399e-79c4-4785-842c-475540b7ccff.png)

![VALIDATOR EXIT – 3](https://user-images.githubusercontent.com/82385103/185387979-32eeeb3a-6f94-4c66-b1bb-2f46ea792912.png)

![VALIDATOR EXIT – 5](https://user-images.githubusercontent.com/82385103/185387858-9fdfe54d-799f-470d-9461-af41eea45772.png)

**Comment by daGscheid** [comment]
User has to input Validator Password to start Task. 
The extra warnings are currently especially necssary as steps to keep people from accidently reeking themselves.

**Comment by stefa2k** [comment]
Removing this from the milestone. No API implementation yet on clients.

**Comment by daGscheid** [comment]
Through changes, in client development we will remove the exit chain option to become a withdrawal option with the Shanghai Update. See #944
