### ISSUE TITLE
Checkpoint Sync doesn't work with Nimbus eth2

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#683]
When entering a correct and working cl node (e. g. infura) nimbus fails to start:
```
Unrecognized option 'trusted-node-url'
Try nimbus_beacon_node --help for more information.
```

**Comment by NeoPlays** [comment]
I may have been to fast implementing this 😅 seems like syncing from a trusted src is an action other than a startup property: [nimbus](https://github.com/status-im/nimbus-eth2/issues/3285)

**Comment by stefa2k** [comment]
solution would be to run 2 commands after each other:
1. checkpoint sync command: finishes when checkpoint sync was successful or when beacon chain database already exists
2. normal beacon chain command
