### ISSUE TITLE
Track - Tutorial Integration

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#686]
![image](https://user-images.githubusercontent.com/82385103/185654182-537ac4d3-edef-4506-afcc-fcec248e379e.png)

> - [ ] POST WORK CHECK - if usable in Stereum

## ETHEREUM GUIDES (available on Ethereum Mainnet, Ethereum Testnets)

<br>

### Stake with 32 ETH
---

- [ ] VIDEO - https://www.youtube.com/watch?v=Cbu58ee_Wj4&ab_channel=Stereum)
- [x] GUIDED 
<br>
<br>

### Use SSV Network
---
- [ ] VIDEO - https://youtu.be/ccKoalZtjlA
- [ ] GUIDED
<br>
<br>

### Alerts on Mobile App (Waiting for full integration) 
---
- [ ] VIDEO - 
- [ ] GUIDED 
<br>
<br>

### Switch Clients (Comes with Custom Installation)
---
- [ ] VIDEO - 
- [ ] GUIDED 
<br>
<br>

### Node Migration (Could be done today, but comes with Custom Installation)
---
- [ ] VIDEO - 
- [ ] GUIDED 
<br>
<br>

### Node RPC Connection
---
- [ ] VIDEO - https://youtu.be/iFzSdjg9r6U
- [x] GUIDED 

<br>
<br>

## GUIDES (available on Gnosis Mainnet)

<br>

### Stake with 1 GNO
---
- [ ] VIDEO 
- [ ] GUIDED

<br>
<br>

### Alerts on Mobile App
---
- [ ] VIDEO 
- [ ] GUIDED

<br>
<br>

### Switch Clients
---
- [ ] VIDEO 
- [ ] GUIDED

<br>
<br>

### Node Migration
---
- [ ] VIDEO 
- [ ] GUIDED

<br>
<br>

### Node RPC Connection
---
- [ ] VIDEO 
- [ ] GUIDED

<br>
<br>

**Comment by daGscheid** [comment]
With the relaunch of the website and the ever-closer coming full release of 2.0.0, I would start up the work for the tutorial integration. To do this, first, I propose a change to the current layout. 

![image](https://user-images.githubusercontent.com/82385103/232053072-a5c815b9-d4b0-487e-8f54-950d1be84351.png)

...better hiding the tutorials to leave more space for notifications. 
With this change you can open our tutorial treasury up, that we can backfill this way without any UX problems. 

![image](https://user-images.githubusercontent.com/82385103/232054009-fe685b05-9640-4ce5-810e-99e98ec72d7f.png)

**Comment by mabasian** [comment]
it's done!

**Comment by daGscheid** [comment]
changed how this is formatted, rest of tasks will be done with #908 after #1067 is closed
