### ISSUE TITLE
When using logout old ssh tunnels still work

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#687]
After logging in, opening up grafana, then logging out and logging in to another node, the old ssh tunnel to the old grafana still works.

@daGscheid Is this desired because we already plan multi-node connections? How is this transparent to the user, accessing multiple Grafanas?

**Comment by daGscheid** [comment]
I could see use case.  I would say we should tend to be less restrictive, if doesn't create additional problems - but I would like to bring that up for discussion - I have no overview of potential problems arising especially security wise & if that is actually useable if they for example share the same port on two different machines.
