### ISSUE TITLE
Nethermind stuck syncing

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#688]
When setting up a testnet node with nethermind as el, nethermind syncs up until rouchgly block 7400000 and get's stuck.

```
2022-08-19 12:09:54.3619|Downloaded 7382981 / 7432977 | current     0.00bps | total     0.00bps
```

**Comment by daverolo** [comment]
The Prometheus labels `nethermind_blocks` and `nethermind_blocks_sealed` are always zero, thus the Sync Status Widget shows always 0/0 for this client.
