### ISSUE TITLE
Status of services break when selecting one for start/stop

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#689]
When I click to stop or start SSV Network plugin the status of the Teku validator plugin also spinns although there is no start/stop of the Teku going on.

![image](https://user-images.githubusercontent.com/54934211/185789157-15aa869f-de30-41b7-9866-916115fa9918.png)

Looks like just a display glitch to me.

**Comment by maxbehzadi82** [comment]
I know the problem.Will be fixed on Monday.
