### ISSUE TITLE
SSV Network expert mode

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#691]
SSV Network also got an additional config file, the `config.yaml` which should also be editable like the service's yaml.

**Comment by daGscheid** [comment]
What does this config.yaml include information-wise?

**Comment by stefa2k** [comment]
just display it the same way as the service's yaml

**Comment by daGscheid** [comment]
> just display it the same way as the service's yaml

Yeah, would do exactly that. Just thinking about how to name the "setting"

**Comment by daGscheid** [comment]
ICON FOR THE SETTING
![SSV_Network_Config](https://user-images.githubusercontent.com/82385103/199579513-147667ae-7482-48de-baa0-59145d950283.png)


Should be called - "SSV CONFIG" & work the same as the expert mode

![SERVICE_SETTING_MODULE](https://user-images.githubusercontent.com/82385103/199580563-0c26cdd4-75c8-4bd3-9f5f-335a7d807312.png)
