### ISSUE TITLE
BUG: Loading a saved connectino doesn't work when using ssh key

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#704]
**Describe the bug**
When selecting and loading a saved connection from the list with a ssh key, login isn't responding anymore. Selecting the very same ssh key again with the file selector and the login button works again.

**To Reproduce**
1. Open Launcher
2. Select a saved connection with a ssh key
3. Press login button
4. Nothing happens

**Expected behavior**
Login should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version 2.0-rc1

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: 

**Additional context**

**Comment by NeoPlays** [comment]
The error is:
```
An invalid form control with name='keylocation' is not focusable.
```

When you reselect the file it works.
Probably some issues with loading the saved connection into the form.
