### ISSUE TITLE
BUG: List/import of validator keys possible while setup is in progress

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#705]
**Describe the bug**
When setup is in progress it's still possible to list and import validator accounts

**To Reproduce**
1. Setup new node (don't wait to completion)
2. Immediately access "Staking" page
3. Import validator accounts

**Expected behavior**
It should not be possible to:
- list validator accounts when service isn't running
- import validator accounts when service isn't running and list validator isn't possible

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/186476950-7dbd01fa-6459-4830-a81a-8fcd4a28ba3e.png)
![image](https://user-images.githubusercontent.com/54934211/186476970-cb9a3fd6-268f-4fe7-a5e7-18d8e7319cf2.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version: 2.0-rc1

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Nimbus 22.8.0

**Additional context**

**Comment by stefa2k** [comment]
Import works when nimbus and geth are in sync.

**Comment by maxbehzadi82** [comment]
Should I disable all pages during installation or only importing?
