### ISSUE TITLE
BUG: importing validators failed "Cannot read property 'some' of undefined"

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#711]
**Describe the bug**
importing validators failed with "Cannot read property 'some' of undefined"

**To Reproduce**
Unknown

**Expected behavior**
Import successful

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/187156232-1ab78827-5a50-4a86-a41b-ae1b55b86910.png)

**Desktop (please complete the following information):**
 - OS: unknown
 - Launcher version 2.0-rc1

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: nimbus

**Additional context**
Looks like an issue here:
https://github.com/stereum-dev/ethereum-node/blob/9ff5f983f361768ea809e8523cb03aefc2cff1d5/launcher/src/backend/ValidatorAccountManager.js#L113

**Comment by NeoPlays** [comment]
This is caused when the import itself fails 
#447

**Comment by stefa2k** [comment]
closing, will be fixed with #447
