### ISSUE TITLE
FR: Offline purne Geth

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#719]
**Is your feature request related to a problem? Please describe.**
Right now it's not possible to prune geth with Stereum. Pruning geth is necessary to free up space.

**Describe the solution you'd like**
A button in the settings of the plugin to start the pruning process would make it easy for users to free up space again. There should also be a warning before executing the pruning process to alert the user the Ethereum full node will be offline until it finishes.

**Describe alternatives you've considered**
Waiting for online pruning - might take a while.

**Additional context**

**Comment by daGscheid** [comment]
CLICK to PROMPT
![Settings - Execution Clients](https://user-images.githubusercontent.com/82385103/187680005-54832589-00e5-4242-aebb-3c4685ddd888.png)


CONFIRM TO START
![PLUGIN SETTINGS](https://user-images.githubusercontent.com/82385103/187680492-e9db0e25-8061-46c9-a945-cfbcd1490222.png)


CHANGE BUTTON WHILE OPERATION RUNS
![PLUGIN SETTINGS-1](https://user-images.githubusercontent.com/82385103/187680488-b8262613-0fc0-4793-8e6c-ffacbdb0d47b.png)
![PLUGIN SETTINGS-2](https://user-images.githubusercontent.com/82385103/187680824-f025abd6-65ec-4bd4-86c3-6ba12ff1b748.png)

POTENTIALLY TO DISCUSSS:
Additional UI elements preferable? Somewhere else for better clarity of progress when prunning?

**Comment by daGscheid** [comment]
@stefa2k Does Nethermind / Besu support Prunning?

**Comment by maxbehzadi82** [comment]
I will add a warning pop-up on it before prunning starts.

**Comment by daGscheid** [comment]
Not sure if necessary - you click INITIATE (flag for initiation) -> click confirm -> we close model & start prunning process (if you should reopen the setttings you see 3rd image)

**Comment by maxbehzadi82** [comment]
Ok. I thought Stafan asked for that.

**Comment by daGscheid** [comment]
Ahhhhh - So you click, we throw a pop up to click away with this info: 

> alert the user the Ethereum full node will be offline until it finishes.

And then start when user confirms. I am fine with that. 

Can we show progress or anything similiarish?

**Comment by NeoPlays** [comment]
The service setting windows are not really made for complex stuff.
I have some ideas. If we stick with the pruning process of stereum 1 then there will be a ansible role to execute.
This is easily doable, but any more functions on the javascript side will take me some more time.

**Comment by stefa2k** [comment]
> @stefa2k Does Nethermind / Besu support Prunning?

Besu got online pruning which needs to be enabled: https://besu.hyperledger.org/en/stable/public-networks/concepts/data-storage-formats/#pruning
Nethermind's full pruning (online pruning) and how to enable it: https://medium.com/nethermind-eth/netherminds-full-pruning-is-here-cutting-the-gordian-knot-5e3450f02de9

So switching on pruning for Besu and Nethermind is just a change in settings, for Geth it's a process that's need to start.

**Comment by daGscheid** [comment]
> Besu got online pruning which needs to be enabled: https://besu.hyperledger.org/en/stable/public-networks/concepts/data-storage-formats/#pruning Nethermind's full pruning (online pruning) and how to enable it: https://medium.com/nethermind-eth/netherminds-full-pruning-is-here-cutting-the-gordian-knot-5e3450f02de9
> 
> So switching on pruning for Besu and Nethermind is just a change in settings, for Geth it's a process that's need to start.

I guess that would be an extra option then - at least from the UI perspective? 
-> "AUTO"-PRUNNING with option being enabled /disabled 

> Progress is not possible, maybe an animation?

Okay, so we go image 1, you click initiate - we throw info you can click away - then you are at image 2 you confirm in the settings. We throw you back to the Node page and play an animation, circumventing the user from fucking around. We play the animation as long as the task runs, if it successful or runs into an error we throw an extra status, you can only click away.

**Comment by stefa2k** [comment]
> I guess that would be an extra option then - at least from the UI perspective: -> "AUTO"-PRUNNING with option being enabled /disabled

See #723 and #724 for this.

Please keep in mind that Geth might be the most important one, followed by Besu. Nethermind has a pruning module turned on by default already.

**Comment by daGscheid** [comment]
After talking Max and I decided on this: 
![prunning](https://user-images.githubusercontent.com/82385103/188025584-68c3cb52-2bd3-4465-9bbe-26d904b65050.png)
Functioning like a on and of switch....
![PRUNNING - 2](https://user-images.githubusercontent.com/82385103/188025590-50f26a31-5e7f-4767-ba36-904421aa3cfb.png)


...only starting when CONFIRMING is pressed, opening a new screen and starting the process
![PRUNNING - 3](https://user-images.githubusercontent.com/82385103/188025594-3aeeb01d-38d8-460d-8d9c-b7603e87d4ff.png)


IN CASE OF SUCCESS
![PRUNNING - 4](https://user-images.githubusercontent.com/82385103/188025623-fa3e1d5e-2e25-4f83-9221-ff5cdb254ccf.png)

IN CASE OF FAILURE
![PRUNNING - 5](https://user-images.githubusercontent.com/82385103/188025717-ec1b2880-87c4-43ff-82b1-a81a36f4e01b.png)

**Comment by stefa2k** [comment]
This raises a couple questions:
1. Can you click somehow close the pruning modal window?
2. When I close it, or just re-login to the node, how do I open it again?
3. How to prevent the user from starting geth while pruning is still in progress?

**Comment by NeoPlays** [comment]
can we close this or will there be some ui for this too? #768

**Comment by daGscheid** [comment]
> can we close this or will there be some ui for this too? #768

Should be able to close it.
