### ISSUE TITLE
BUG: UI: Managing of validators on HiDPI screen requires workarounds

### ISSUE THREAD

**Issue by pepawel** [stereum-dev/ethereum-node#731]
**Describe the bug**
When using HiDPI screen (3840x2160 resolution with 200% scaling) UI in "Staking" tab doesn't work well. The button to add validator key doesn't respond to click.

**To Reproduce**
1. Go to "Staking" tab.
2. Observe elements near the button at the bottom are misplaced.
3. Click "CLICK OR DRAG TO INSERT KEY" button.
4. Observe nothing happens.

**Expected behavior**
File selector should appear.

**Desktop:**
 - OS: Pop!_OS Linux
 - Screen resolution: 3840x2160
 - Scaling factor: 200%
 - Launcher version: 2.0-RC2

**Node:**
 - OS: Ubuntu 20.04
 - Affected service: Lighthouse

**Additional context**
When I decrease the height of the Stereum window to 1/2 of screen height, the issue disappears and the UI starts to work.

**Comment by NeoPlays** [comment]
The window size of stereum is fixed for quite some time now. so i think this issue won't occur anymore.
I'll close this one because there already is an open issue which focuses on responsive window size in gerneral.
