### ISSUE TITLE
BUG: Staking page just shows a subset of staking keys

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#736]
**Describe the bug**
On a server with 10+ keys there's only a subset of the keys displayed on the Staking page.

**To Reproduce**
1. Import 10+ keys
2. Restart Stereum Launcher
3. Open up Staking page
4. Only some of the keys show up

**Expected behavior**
All keys show up in the list.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0-rc2`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Stereum Launcher

**Comment by NeoPlays** [comment]
i wasn't able to reproduce this so if you could provide ansible logs of the `validator-list-api` role, that would be awesome 😅

**Comment by stefa2k** [comment]
Hm, now it works... closing it for now.
