### ISSUE TITLE
BUG: text on icons not readable

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#744]
**Describe the bug**
The text "validator client" is not readable on the icons.

**Expected behavior**
The text ist clearly readable.

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/189074787-28925e44-c83e-4621-b82d-775a3d0a6eae.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0-rc2`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: all validator services

**Comment by daGscheid** [comment]
Could you include the following next release @maxbehzadi82 
![Teku - Validator Clients](https://user-images.githubusercontent.com/82385103/189542200-8965b1d0-4a9f-42f4-b996-d0c01b34fd99.png)
![Prysm - Validator Clients](https://user-images.githubusercontent.com/82385103/189542202-d524c35f-aa2c-466b-b06a-7fc8a62779cb.png)
![Nimbus - Validator Clients](https://user-images.githubusercontent.com/82385103/189542203-db989f9c-c28f-4bca-ab2b-2d0fd8d474b3.png)
![Lighthouse - Validator Clients](https://user-images.githubusercontent.com/82385103/189542204-494ba0fc-ecde-4c41-abb0-ef350f16c649.png)


![Nimbus - Validator Clients - Circle](https://user-images.githubusercontent.com/82385103/189542228-b8280416-3633-4dd7-971e-6ce8280e13c1.png)
![Lighthouse - Validator Clients - Circle](https://user-images.githubusercontent.com/82385103/189542225-d8f8f521-4342-4113-901b-c37ee40d3dde.png)
![Teku - Validator Clients - Circle](https://user-images.githubusercontent.com/82385103/189542226-ee924d20-5b8b-42a6-970e-096946b9e6ee.png)
![Prysm - Validator Clients - Circle](https://user-images.githubusercontent.com/82385103/189542227-c9c9c8bd-2f1b-4de6-af52-6b14492b8ed8.png)

**Comment by maxbehzadi82** [comment]
Sure.Send me plz the icons.
