### ISSUE TITLE
BUG: Updating a single service doesn't restart it

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#781]
**Describe the bug**
When updating only one service then the update runs fine, but the service doesn't restart automatically.

**To Reproduce**
1. Open Update Panel
2. Click on one service to update

**Expected behavior**
When updating a single service the updater should also restart the service. Otherwise the old version still keeps running.

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/190891180-661f41dc-ce72-41ea-8517-2861ddf216b0.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0-rc3`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: all

**Comment by NeoPlays** [comment]
<img width="247" alt="grafik" src="https://user-images.githubusercontent.com/80448387/190963256-09a958d2-c532-41d4-81f8-ec938a4bd6ea.png">

```
d67e5d630f95   ethereum/client-go:v1.10.25   "geth --goerli --dat…"   20 seconds ago   Up Less than a second   8545-8546/tcp, 127.0.0.1:8551->8551/tcp, 0.0.0.0:30303->30303/tcp, 0.0.0.0:30303->30303/udp   stereum-e15597fb-dadf-c58e-db45-40df17faf1f7
```

So I tried this on my vm and it worked as supposed. Maybe a timing issue?
