### ISSUE TITLE
BUG: can't copy validator key

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#800]
**Describe the bug**
When clicking the button to copy the validator key to clipboard, nothing happens.

**To Reproduce**
1. Go to Staking page
2. Click on copy validator key
3. Try paste it somewhere

**Expected behavior**
validator key in the clipboard

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `2.0.0-rc.4`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Staking page

**Comment by NeoPlays** [comment]
`Copy` doesn't work anywhere atm.
The copy functions need to be rewritten.
