### ISSUE TITLE
FR: Integration of web3signer

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#829]
**Is your feature request related to a problem? Please describe.**
Using the web3signer of Consensys will make setups more flexible: https://github.com/ConsenSys/web3signer

**Describe the solution you'd like**
Integration of web3signer as a validator service.

**Describe alternatives you've considered**

**Comment by daGscheid** [comment]
![image](https://user-images.githubusercontent.com/82385103/211538357-632eee76-36cc-4c88-a724-804ddc2b5d9e.png)
![image](https://user-images.githubusercontent.com/82385103/211538401-fb52a735-7a40-478d-a7fc-69bcb85f9e9b.png)

Docs can be found here: https://docs.web3signer.consensys.net/en/latest/
