### ISSUE TITLE
Finalize MEV Boost Service Modal >.>

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#837]
Includes:

-) Make MEV Boost Service Modell accessible on the top bar
-) Make it possible to select / change & confirm the relay selection. 

**Optional**
-) Link / Show an overview of the current Relay Distribution
https://www.mevboost.org/

**Comment by maxbehzadi82** [comment]
For the next release, you mean?

**Comment by daGscheid** [comment]
> For the next release, you mean?

Si senior. Ignore this for tomorrow. Tomorrow is MEV test day

**Comment by maxbehzadi82** [comment]
Roger
