### ISSUE TITLE
BUG: Show Service ID of Clients for Modification of Connection in Custom Installation

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#840]
**Describe the bug**
Show the service ID for the Clients when selecting their connection. 

**Screenshots**

**Comment by daGscheid** [comment]
Because of the limited space in the component itself I either propose one of the solutions or a combination of them.

1# changing the displayed text every few seconds 

2# Use a tooltip showing the ID when hovering

3#  When hovering visually change (f.e. with a border) the connected client in question

**Comment by maxbehzadi82** [comment]
Screenshot plz :)

**Comment by daGscheid** [comment]
> Screenshot plz :)

100%. Meant is this: 

![image](https://user-images.githubusercontent.com/82385103/199788085-17543960-616e-4174-a80f-a0c613ea3be9.png)

In this example - it could potentially lead to some problems if you have multiple Geth clients & you don't know which Geth is which. 


1# The text "Geth" would just change into a shortened ID

2# Whenever you are hovering "GETH" you can see the ID in tooltip

3# When hovering Geth or selecting the client - the connected clients (or all the non connected) change visible. 
- I have a few suggestions for this. Still thinking what would be the best. Lets talk Monday

**Comment by maxbehzadi82** [comment]
Sure.

**Comment by daGscheid** [comment]
- [ ] Im "Add"
- [ ] Im "Modify"
