### ISSUE TITLE
FR: Adapt all Dashboard Widgets -  to multiple clients

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#841]
**Is your feature request related to a problem? Please describe.**
With the introduction of Custom Installation it will be possible to run multiple node configurations. To handle this in the dashboard, we have to adapt all of them to f.e. handle multiple clients in sync

**Describe the solution you'd like**
The adaption of the dashboards to the usage of multiple clients / node configurations

**Comment by daGscheid** [comment]
For more than 10 & less than a 100 (we support at max 99 configurations for the dashboard)

![-----](https://user-images.githubusercontent.com/82385103/199005016-ec6e2cf5-cfe0-449d-b737-5d1a7f54417e.png)
![PEER TO PEER NETWORK](https://user-images.githubusercontent.com/82385103/199005023-8f45b6c7-853b-4aa2-9e82-dad610899b74.png)

**Comment by daGscheid** [comment]
@daverolo can be closed?

**Comment by mabasian** [comment]
> 

already done

**Comment by daverolo** [comment]
> @daverolo can be closed?

yep @daGscheid, closed this. done by #894, #901, #906, #912, #925 :clap:
