### ISSUE TITLE
FR: Stereum on ARM

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#853]
**Is your feature request related to a problem? Please describe.**
Run Stereum node on ARM architecture (Raspi4, Rock 5B, ...).

**Describe the solution you'd like**
Supporting Ubuntu on ARM architecture. Stereum automatically detects the architecture and behaves accordingly (commands, docker images, ...)

**Additional context**
https://ethereum-on-arm-documentation.readthedocs.io/en/latest/index.html could be helpful to make ARM supportable.

**Comment by bruderbuck** [comment]
Just wanted to report the problems I ran into when trying to run stereum with the Rock 5b.

I formatted and then mounted the nvme ssd to mnt/ssd and created a folder with permissions for all to read write and execute called stereumData.

When I try to set up the node with stereum and I set the installation point to mnt/ssd/stereumData I am getting these errors.

system is a freshly installed Ubuntu 20.04 from here https://wiki.radxa.com/Rock5/downloads 
![image](https://user-images.githubusercontent.com/95592443/219156899-3e2b7577-581f-402c-8bed-ec7c37bf46cd.png)
![image](https://user-images.githubusercontent.com/95592443/219156999-c3bf8c6e-7570-4912-b77f-e89f1798fde8.png)
