### ISSUE TITLE
Lighthouse: import validator key via rest api

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#91]
lighthouse api: https://lighthouse-book.sigmaprime.io/api.html
importing key api: https://lighthouse-book.sigmaprime.io/api-vc-endpoints.html#post-lighthousevalidatorskeystore

keymanager api specs: https://ethereum.github.io/keymanager-APIs/

**Comment by gbayasgalan** [comment]
https://github.com/stereum-dev/ethereum-node/pull/169
