### ISSUE TITLE
VALIDATOR KEY COMMANDS - advanced - Grouping / Filtering

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#921]
Taken out of #613, pushed back to a later version. 

An additional functionality used to: 
-) GROUP VALIDATOR KEY(s)
-) FILTER VALIDATOR KEY(s) BY NAME / PUBLIC KEY

this also must include a path to:

- move / add to a group
- remove keys from a group

**Comment by MaxTheGeeek** [comment]
FILTER   done.

**Comment by daGscheid** [comment]
@gbayasgalan & @MaxTheGeeek going to finish this up soon
