### ISSUE TITLE
BUG: Teku SNI issue on validator key import

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#958]
**Describe the bug**
Importing validator keys on Teku results in error.

**To Reproduce**
1. Setup Teku `22.12.0`
2. Import keys
3. See error

**Expected behavior**
Import without error

**Screenshots**
![image](https://user-images.githubusercontent.com/54934211/206425735-0c2a0b10-b167-4359-a3ea-3933fc9952d9.png)

**Desktop (please complete the following information):**
 - OS: tba
 - Launcher version tba

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Teku `22.12.0`

**Additional context**
Teku bug, tracked here: https://github.com/ConsenSys/teku/issues/6564

**Comment by alepacheco** [comment]
You can change teku version to 22.11.0 and it seems to work fine

**Comment by ajsutton** [comment]
For the record, this is an issue with the SSL certificate being used, not a Teku bug.  The latest version of Teku started (correctly) verifying that the SSL certificate being used actually matches the domain being requested by the client. There's a draft PR up to document how to create a cert that supports multiple domains and IPs: https://github.com/ConsenSys/doc.teku/pull/414

**Comment by alepacheco** [comment]
The fix could be similar to this https://github.com/eth-educators/eth-docker/pull/1102

**Comment by NeoPlays** [comment]
@alepacheco yes it is ^^ fixed it today. I'm just working on a rollout for existing nodes.
