### ISSUE TITLE
Control Page - No Services 

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#966]
To better track this.
We should disable / deactivate individual components on the control page, whenever:

- [x] the necessary service for the component to function is not installed

![EN - CONTROL TAB - GENERAL CHOICE – 7](https://user-images.githubusercontent.com/82385103/207598894-e41d13c0-be53-4844-ade4-de957a3fc2ec.png)

- [x] the necessary service for the component to function is turned off.

![EN - CONTROL TAB - GENERAL CHOICE – 8](https://user-images.githubusercontent.com/82385103/207598919-612448fd-f6d7-4164-bb04-c0dac2e43f19.png)

Image to fill placeholder is currently in works & will be provided at a later date.

**Comment by daverolo** [comment]
SyncStatus and P2PStatus Widgets now fall back to initial state if Prometheus Service is down (#968).
Data-API and RPC-API Widgets working already as extecpetd (going to init state if no client is up)
In the screenshow below:
- RPC Widget is down because Geth EL is down
- SyncStatus and P2PStatus Widget are down because Prometeus Service is down
- Other Widgets does not have dependencies or not implemented yet ("- COMING SOON -")

![grafik](https://user-images.githubusercontent.com/107847185/207629859-845f7600-66be-40ff-8e24-e00ed7c1c8a2.png)

**Comment by mabasian** [comment]
For turning on the necessary services in the p2p and sync status is done

**Comment by daverolo** [comment]
> @mabasian wrote: "For turning on the necessary services in the p2p and sync status is done"
Now this is how SyncStatus and P2PStatus Widgets look if Prometheus is down:
![grafik](https://user-images.githubusercontent.com/107847185/208085808-f782c708-cc60-426a-9bed-e7fe6339eeba.png)

**Comment by daGscheid** [comment]
Current state: 

**None installed** 
![image](https://user-images.githubusercontent.com/82385103/219652873-79127dbc-d523-4c4d-88d9-c16c94397cde.png)

**Prometheus Turned Off** 

![image](https://user-images.githubusercontent.com/82385103/219654130-ddb7a6a5-d97b-4245-87cb-5becb3c50633.png)

**Execution Client Turned Off**
![image](https://user-images.githubusercontent.com/82385103/219655748-dfe709c7-5436-4764-8322-00b51410bc8f.png)


**Consensus Client Turned Off** 
![image](https://user-images.githubusercontent.com/82385103/219654424-c9c83870-bbcf-4798-b3dc-75fade64bef7.png)

**Validator Client Turned Off** 
![image](https://user-images.githubusercontent.com/82385103/219656573-1f4c863b-5a21-4170-93ff-0fff3ca8715f.png)


Also Staking Page (if there is no validator client installed) -> could need improvements
![image](https://user-images.githubusercontent.com/82385103/219653158-b3a4e764-94d6-468b-90ee-3387553a60f9.png)

**Comment by daGscheid** [comment]
- [ ] Status for Control Page - Balance Widget - when no validator client

**Comment by daGscheid** [comment]
@mabasian please don't forget:

- [ ] Loading State for the slot / epoch viewer 

https://github.com/stereum-dev/ethereum-node/assets/82385103/9ebde119-ed4e-45fa-8b8b-bbf81242961c

- [ ] No Data state (did not test it yet)

**Comment by mabasian** [comment]
@daGscheid If the user turns off the consensus client, it will receive a no-data status

**Comment by daGscheid** [comment]
> @daGscheid If the user turns off the consensus client, it will receive a no-data status

Could you add the same for the Current Slot / Epoch Component as well please 🙏
