### ISSUE TITLE
BUG: Setup with OneClickInstaller for SSV Network stuck

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#992]
**Describe the bug**
Setup with SSV Network with any clients get stuck after "Configure Firewall". There are no other tasks spawning.

**To Reproduce**
1. Setup a new node with OneClickInstaller
2. Select Testnet
3. Select SSV Network
4. Continue until tasks start running
5. Installation stuck

**Expected behavior**
SSV Network setup services get installed properly.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `1.0.0-rc.9`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: SSV Network

**Comment by NeoPlays** [comment]
fixed in #989
