### ISSUE TITLE
BUG: Installing MEV-Boost with Custom Installation with Prysm doesn't wire fully

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#995]
**Describe the bug**
Custom Installer wires to the Prysm Validator service correctly, but not to the Prysm Beacon Chain service. `--http-mev-relay` is missing in the config of Prysm's consensus client.

**To Reproduce**
1. Setup Prysm
2. Add Mev Boost with Custom Installation
3. Open Expert Mode on Prysm's consensus client, no `--http-mev-relay` in it

**Expected behavior**
`--http-mev-relay` get's added with the url to the MEV Boost service.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Launcher version `1.0.0-rc.10`

**Node (please complete the following information):**
 - OS: Ubuntu 22.04
 - Affected service: Prysm

**Comment by NeoPlays** [comment]
> I think I forgot to click on the consensus client to make it green (connected). This explains this issue but raises another one: When I didn't select the consensus client when installing MEV Boost, why was `--enable-builder=true` set on Prysm's validator service after install?

  `--enable-builder, --enable-validator-registration  Enables Builder validator registration APIs for the validator client to update settings such as fee recipient and gas limit. Note* this flag is not required if using proposer settings config file (default: false)`
this has nothing to do with mev-boost
