### ISSUE TITLE
FR: Restart button for services

### ISSUE THREAD

**Issue by stefa2k** [stereum-dev/ethereum-node#996]
**Is your feature request related to a problem? Please describe.**
When changing the config of a service, it must be turned off and on again. 

**Describe the solution you'd like**
A restart button for each service would be a great help.

**Comment by daGscheid** [comment]
To solve this, I had the idea to add an additional button to the Panel - Left on the Node page

![log changes](https://user-images.githubusercontent.com/82385103/216642346-35a7e4e2-2f81-42a2-9b89-a1e448bf2d51.png)
![log changes – 1](https://user-images.githubusercontent.com/82385103/216642353-884661ac-faef-4fe4-bd7d-ae1bcf042dec.png)
![log changes – 2](https://user-images.githubusercontent.com/82385103/216642365-df60b603-8751-4099-a57c-ff2a0c7863aa.png)

Obviously restricting clicking buttons after pressing until the operation is done.

**Comment by stefa2k** [comment]
I like this idea better than having the tiny buttons after clicking the service once. Would it be somehow possible to get big buttons also for start/stop, together with the restart and the status of the service?
